; Common settings for ESP32 OG (without suffix)
; See 'esp32_common' for common ESP32-family settings
[esp32_base]
extends = esp32_common
custom_esp32_kind = esp32

build_src_filter =
  ${esp32_common.build_src_filter}
  -<modules/esp32/PaxcounterModule.cpp>
  -<mesh/http/>

build_flags =
  ${esp32_common.build_flags}
  -DMESHTASTIC_EXCLUDE_AUDIO=1
  -DMESHTASTIC_EXCLUDE_ACCELEROMETER=1
  -DMESHTASTIC_EXCLUDE_PAXCOUNTER=1
  -DMESHTASTIC_EXCLUDE_WEBSERVER=1
  -DMESHTASTIC_EXCLUDE_RANGETEST=1

lib_deps =
  ${arduino_base.lib_deps}
  ${networking_base.lib_deps}
  ${networking_extra.lib_deps}
  ${radiolib_base.lib_deps}
  ${environmental_base.lib_deps}
  ${environmental_extra_no_bsec.lib_deps}
  # renovate: datasource=custom.pio depName=NimBLE-Arduino packageName=h2zero/library/NimBLE-Arduino
  h2zero/NimBLE-Arduino@1.4.3
  # renovate: datasource=custom.pio depName=XPowersLib packageName=lewisxhe/library/XPowersLib
  lewisxhe/XPowersLib@0.3.3
  # renovate: datasource=custom.pio depName=rweather/Crypto packageName=rweather/library/Crypto
  rweather/Crypto@0.4.0
