[env:thinknode_m7]
extends = esp32s3_base
board = ThinkNode-M7

build_flags = 
  ${esp32s3_base.build_flags}
  -D ELECROW_ThinkNode_M7
  -D HAS_UDP_MULTICAST=1
  -D BOARD_HAS_PSRAM
  -I variants/esp32s3/ELECROW-ThinkNode-M7
  -mfix-esp32-psram-cache-issue

lib_ignore = 
    Ethernet

lib_deps =
  ${esp32s3_base.lib_deps}
  # renovate: datasource=github-tags depName=ESP32-CH390 packageName=meshtastic/ESP32-CH390
  https://github.com/meshtastic/ESP32-CH390/archive/refs/tags/v1.0.1.zip