; LilyGo T-Connect-Pro
[env:t-connect-pro]
custom_meshtastic_hw_model = 147
custom_meshtastic_hw_model_slug = T_CONNECT_PRO
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = LILYGO T-Connect Pro
custom_meshtastic_tags = LilyGo
custom_meshtastic_partition_scheme = 16MB

extends = esp32s3_base
board_level = release
board = t-connect-pro
board_build.partitions = default_16MB.csv
upload_protocol = esptool

build_flags =
  ${esp32s3_base.build_flags}
  -I variants/esp32s3/t-connect-pro
  -D T_CONNECT_PRO
  -D HAS_UDP_MULTICAST=1
  -D RADIOLIB_EXCLUDE_SX127X=1
  -D RADIOLIB_EXCLUDE_SX128X=1
  -D RADIOLIB_EXCLUDE_LR11X0=1

lib_deps =
  ${esp32s3_base.lib_deps}
  # renovate: datasource=custom.pio depName=LovyanGFX packageName=lovyan03/library/LovyanGFX
  lovyan03/LovyanGFX@1.2.28
  # renovate: datasource=custom.pio depName=SensorLib packageName=lewisxhe/library/SensorLib
  lewisxhe/SensorLib@0.4.1

custom_sdkconfig =
  ${esp32s3_base.custom_sdkconfig}
  CONFIG_ETH_ENABLED=y
  CONFIG_ARDUINO_SELECTIVE_Ethernet=y
