[env:supermini_wio_sx1262_v1]
extends = esp32c3_base
board = esp32-c3-devkitm-1
board_level = extra
build_flags =
  ${esp32c3_base.build_flags}
  -I variants/esp32c3/diy/stm32c3_wio_sx1262
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
