[env:esp32s3-e22-w5500]
extends = esp32s3_base
board = esp32-s3-devkitc-1
board_level = extra
board_check = true
board_build.partitions = default_16MB.csv
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi

build_unflags =
  ${esp32s3_base.build_unflags}
  -D LED_BUILTIN=-1

build_flags =
  ${esp32s3_base.build_flags}
  -D PRIVATE_HW
  -D BOARD_HAS_PSRAM
  -D MESHTASTIC_EXCLUDE_WEBSERVER=1
  -D MESHTASTIC_TCP_API_MAX_CLIENTS=4
  -D MESHTASTIC_TCP_API_IDLE_TIMEOUT_MS=120000
  -D HAS_UDP_MULTICAST=1
  -I variants/esp32s3/diy/esp32s3-e22-w5500

lib_ignore =
  Ethernet

lib_deps =
  ${esp32s3_base.lib_deps}
  https://github.com/meshtastic/ETHClass2/archive/v1.0.0.zip
