[crowpanel_epaper_base]
extends = esp32s3_base, niche
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.partitions = default_8MB.csv
board = esp32-s3-devkitc-1
;upload_port = /dev/ttyUSB0
board_level = extra
upload_protocol = esptool
build_src_filter =
  ${esp32s3_base.build_src_filter}
  ${niche.build_src_filter}
build_flags =
  ${esp32s3_base.build_flags}
  ${niche.build_flags}
  -I variants/esp32s3/crowpanel-esp32s3-5-epaper
  -D PRIVATE_HW
  -DBOARD_HAS_PSRAM
lib_deps =
  ${esp32s3_base.lib_deps}

[env:crowpanel-esp32s3-5-epaper]
extends = crowpanel_epaper_base
build_flags =
  ${crowpanel_epaper_base.build_flags}
  -D CROWPANEL_ESP32S3_5_EPAPER

[env:crowpanel-esp32s3-4-epaper]
extends = crowpanel_epaper_base
build_flags =
  ${crowpanel_epaper_base.build_flags}
  -D CROWPANEL_ESP32S3_4_EPAPER

[env:crowpanel-esp32s3-2-epaper]
extends = crowpanel_epaper_base
build_flags =
  ${crowpanel_epaper_base.build_flags}
  -D CROWPANEL_ESP32S3_2_EPAPER
