[vigil_base]
extends = esp32s3_base
board = heltec_v4
board_check = true
board_build.partitions = default_16MB.csv
build_flags =
  ${esp32s3_base.build_flags}
  -D HELTEC_V4
  -D HAS_VIGIL=1
  -D HAS_LORA_FEM=1
  -I variants/esp32s3/vigil
  -ULED_BUILTIN

[env:vigil]
custom_meshtastic_hw_model = 110
custom_meshtastic_hw_model_slug = HELTEC_V4
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = Vigil Acoustic C-UAS
custom_meshtastic_tags = Vigil,Heltec

extends = vigil_base
build_flags =
  ${vigil_base.build_flags}
  -D HELTEC_V4_OLED
  -D USE_SSD1306
  -D LED_POWER=35
  -D RESET_OLED=21
  -D I2C_SDA=17
  -D I2C_SCL=18
  -D I2C_SDA1=4
  -D I2C_SCL1=3
