; Meshtastic DIY v1 by Nano VHF Schematic based on ESP32-WROOM-32 (38 pins) devkit & EBYTE E22 SX1262/SX1268 module
[env:meshtastic-diy-btclassic]
custom_meshtastic_hw_model = 39
custom_meshtastic_hw_model_slug = DIY_V1
custom_meshtastic_architecture = esp32
custom_meshtastic_actively_supported = false
#custom_meshtastic_support_level = 3
custom_meshtastic_display_name = DIY btclassic
custom_meshtastic_images = diy.svg
custom_meshtastic_tags = DIY

extends = esp32_base
board = esp32doit-devkit-v1
board_check = true
#TODO remove Nimble dependency

build_flags =
  ${esp32_base.build_flags}
  -D DIY_V1
  -D EBYTE_E22
  # WIP - so firmware fits in size, awaiting disable nimble
  -DMESHTASTIC_EXCLUDE_GPS=1
  -DMESHTASTIC_EXCLUDE_MQTT=1
  #-D MESHTASTIC_EXCLUDE_BLUETOOTH
  #-D CONFIG_BT_ENABLED
  #-D CONFIG_BLUEDROID_ENABLED
  -D MESHTASTIC_ENABLE_BLUETOOTHCLASSIC
  -I variants/esp32/diy/btclassic

lib_deps =
  ${arduino_base.lib_deps}
  ${networking_base.lib_deps}
  ${networking_extra.lib_deps}
  ${radiolib_base.lib_deps}
  ${environmental_base.lib_deps}
  ${environmental_extra_no_bsec.lib_deps}
  # renovate: datasource=custom.pio depName=NimBLE-Arduino packageName=h2zero/library/NimBLE-Arduino
  # TODO DISABLE
  h2zero/NimBLE-Arduino@1.4.3
  # renovate: datasource=custom.pio depName=XPowersLib packageName=lewisxhe/library/XPowersLib
  lewisxhe/XPowersLib@0.3.3
  # renovate: datasource=custom.pio depName=rweather/Crypto packageName=rweather/library/Crypto
  rweather/Crypto@0.4.0
