[env:wt32-eth01-e22]
extends = esp32_base
board = esp32dev
board_build.partitions = partition-table.csv
upload_speed = 115200
build_flags =
  ${esp32_base.build_flags}
  -I variants/esp32/wt32-eth01-e22
  -D WT32_ETH01_E22
  -D HAS_ETHERNET=1
  -D ETH_PHY_TYPE=ETH_PHY_LAN8720
  -D ETH_PHY_ADDR=1
  -D ETH_TYPE=0
  -D MESHTASTIC_EXCLUDE_WEBSERVER=1
  -D MESHTASTIC_EXCLUDE_PKT_LOG=1
  -D MESHTASTIC_EXCLUDE_AUDIO=1
  -D MESHTASTIC_EXCLUDE_STOREFORWARD=1