[env:mini-epaper-s3]
;custom_meshtastic_hw_model =
custom_meshtastic_hw_model_slug = MINI_EPAPER_S3
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = LILYGO Mini ePaper S3 E-Ink
custom_meshtastic_tags = LilyGo
custom_meshtastic_requires_dfu = no

extends = esp32s3_base
board = mini-epaper-s3
board_check = true
upload_protocol = esptool

build_flags =
  ${esp32s3_base.build_flags}
  -I variants/esp32s3/mini-epaper-s3
  -D MINI_EPAPER_S3
  -D USE_EINK
  -D EINK_DISPLAY_MODEL=GxEPD2_102
  -D EINK_WIDTH=128
  -D EINK_HEIGHT=80
  -D USE_EINK_DYNAMICDISPLAY
  -D EINK_LIMIT_FASTREFRESH=3
  -D EINK_LIMIT_RATE_BACKGROUND_SEC=30
  -D EINK_LIMIT_RATE_RESPONSIVE_SEC=1
  -D EINK_BACKGROUND_USES_FAST
  -D EINK_HASQUIRK_GHOSTING

lib_deps =
  ${esp32s3_base.lib_deps}
  # renovate: datasource=git-refs depName=meshtastic-GxEPD2 packageName=https://github.com/meshtastic/GxEPD2 gitBranch=master
  https://github.com/meshtastic/GxEPD2/archive/c7eb4c3c167cf396ef4f541cc5d4c6aa42f3c46b.zip
  # renovate: datasource=custom.pio depName=SensorLib packageName=lewisxhe/library/SensorLib
  lewisxhe/SensorLib@0.3.4

[env:mini-epaper-s3-inkhud]
extends = esp32s3_base, inkhud
board = mini-epaper-s3
board_check = true
upload_protocol = esptool
build_src_filter =
  ${esp32s3_base.build_src_filter}
  ${inkhud.build_src_filter}
build_flags =
  ${esp32s3_base.build_flags}
  ${inkhud.build_flags}
  -I variants/esp32s3/mini-epaper-s3
  -D MINI_EPAPER_S3
lib_deps =
  ${inkhud.lib_deps} ; InkHUD libs first, so we get GFXRoot instead of AdafruitGFX
  ${esp32s3_base.lib_deps}
  # renovate: datasource=custom.pio depName=SensorLib packageName=lewisxhe/library/SensorLib
  lewisxhe/SensorLib@0.3.4
