[env:seeed_wio_tracker_L2]
custom_meshtastic_hw_model = 99 ; TODO: assign a unique number to this hardware model
custom_meshtastic_hw_model_slug = SEEED_WIO_TRACKER_L2
custom_meshtastic_architecture = esp32s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = Seeed Wio Tracker L2
custom_meshtastic_images = wio_tracker_l2_case.svg
custom_meshtastic_tags = Seeed
custom_meshtastic_requires_dfu = true

board = seeed_wio_tracker_L2
board_level = pr
extends = esp32s3_base
board_check = true
upload_protocol = esptool
board_build.partitions = default_16MB.csv
build_flags = ${esp32s3_base.build_flags} 
  -I variants/esp32s3/seeed_wio_tracker_L2
  -D SEEED_WIO_TRACKER_L2
  -D CONFIG_ARDUHAL_ESP_LOG
  -D CONFIG_ARDUHAL_LOG_COLORS=1
  -D CONFIG_DISABLE_HAL_LOCKS=1
  -D MESHTASTIC_EXCLUDE_WEBSERVER=1
  -D LV_LVGL_H_INCLUDE_SIMPLE
  -D LV_CONF_INCLUDE_SIMPLE
  -D LV_COMP_CONF_INCLUDE_SIMPLE
  -D INPUTDRIVER_BUTTON_TYPE=0
  -D LV_USE_LOG=0
  -D LV_BUILD_TEST=0
  -D USE_LOG_DEBUG
  -D LOG_DEBUG_INC=\"DebugConfiguration.h\"
  -D RADIOLIB_SPI_PARANOID=0
  -D HAS_SCREEN=0
  -D HAS_TFT=1
  -D USE_I2S_BUZZER
  -D HAS_SDCARD
  -D HAS_SD_MMC ; SDIO mode 1-bit
  -D SD_SCLK_PIN=2
  -D SD_MOSI_PIN=3 ; CMD
  -D SD_MISO_PIN=1 ; D0
  -D SDCARD_CS=-1
  -D RAM_SIZE=5120
  -D LGFX_BUFSIZE=115200
  -D LV_CACHE_DEF_SIZE=2097152
  -D DISPLAY_SIZE=320x240 ; landscape mode
  -D LGFX_DRIVER=LGFX_WIO_TRACKER_L2
  -D GFX_DRIVER_INC=\"graphics/LGFX/LGFX_WIO_TRACKER_L2.h\"
  -D VIEW_320x240
  -D MAP_FULL_REDRAW
  -D USE_PACKET_API


build_src_filter = ${esp32s3_base.build_src_filter} +<../variants/esp32s3/seeed_wio_tracker_L2>
lib_deps =
  ${esp32s3_base.lib_deps}
  ${device-ui_base.lib_deps}
  # renovate: datasource=git-refs depName=ESP8266Audio packageName=https://github.com/meshtastic/ESP8266Audio gitBranch=meshtastic-2.0.0-dacfix
  https://github.com/meshtastic/ESP8266Audio/archive/343024632ee78d6216907b2353fc943a62422d80.zip
  # renovate: datasource=custom.pio depName=ESP8266SAM packageName=earlephilhower/library/ESP8266SAM
  earlephilhower/ESP8266SAM@1.1.0
  # renovate: datasource=github-tags depName=pschatzmann_arduino-audio-driver packageName=pschatzmann/arduino-audio-driver
  https://github.com/pschatzmann/arduino-audio-driver/archive/v0.2.1.zip
  # renovate: datasource=github-tags depName=RobTillaart_TCA9555 packageName=RobTillaart/TCA9555
  https://github.com/RobTillaart/TCA9555/archive/refs/tags/0.4.4.zip
  # renovate: datasource=github-tags depName=LovyanGFX packageName=lovyan03/LovyanGFX
  https://github.com/lovyan03/LovyanGFX/archive/c1b1e3b459de8d281466afbb8ae002c58745288e.zip
