[env:heltec-rc32]
custom_meshtastic_hw_model = 141
custom_meshtastic_hw_model_slug = HELTEC_RC32
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_display_name = Heltec RC32
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_images = heltec_rc32.svg
custom_meshtastic_tags = Heltec
custom_meshtastic_requires_dfu = true
custom_meshtastic_partition_scheme = 16MB
custom_meshtastic_has_mui = false

extends = esp32s3_base
board = heltec-rc32
board_check = true
board_level = extra
board_build.partitions = default_16MB.csv
build_flags =
  ${esp32s3_base.build_flags}
  -D HELTEC_RC32
  -D USE_PIN_BUZZER=PIN_BUZZER
  -D BOARD_HAS_PSRAM
  -I variants/esp32s3/heltec_rc32
lib_deps =
  ${esp32s3_base.lib_deps}
  https://github.com/Quency-D/Arduino_GFX/archive/4d5afb05ce70a51895fe65efc7838d606b2a95a7.zip
