#pragma once

#include_next "sdkconfig.h"

// qio_opi enables this, but Meshtastic removes the matching IDF component.
#ifdef CONFIG_NETWORK_PROV_NETWORK_TYPE_WIFI
#undef CONFIG_NETWORK_PROV_NETWORK_TYPE_WIFI
#endif
#define CONFIG_NETWORK_PROV_NETWORK_TYPE_WIFI 0

#ifndef CONFIG_LITTLEFS_PAGE_SIZE
#define CONFIG_LITTLEFS_MAX_PARTITIONS 3
#define CONFIG_LITTLEFS_PAGE_SIZE 256
#define CONFIG_LITTLEFS_OBJ_NAME_LEN 64
#define CONFIG_LITTLEFS_READ_SIZE 128
#define CONFIG_LITTLEFS_WRITE_SIZE 128
#define CONFIG_LITTLEFS_LOOKAHEAD_SIZE 128
#define CONFIG_LITTLEFS_CACHE_SIZE 512
#define CONFIG_LITTLEFS_BLOCK_CYCLES 512
#define CONFIG_LITTLEFS_USE_MTIME 1
#define CONFIG_LITTLEFS_MTIME_USE_SECONDS 1
#define CONFIG_LITTLEFS_MALLOC_STRATEGY_DEFAULT 1
#define CONFIG_LITTLEFS_ASSERTS 1
#endif
