#include "TDeckUiPolicy.h"

#include "graphics/ScreenFonts.h"

const DeviceUiMetrics &TDeckUiPolicy::metrics() const
{
    static const DeviceUiMetrics metrics = {
        true,
        FONT_SMALL_LOCAL,
        FONT_SMALL_LOCAL,
        deviceUiDefaultFontSmall,
        deviceUiDefaultFontSmall,
        deviceUiDefaultFontMedium,
        deviceUiDefaultFontLarge,
        8,
        16,
        50,
        4,
        4,
        102,
        72,
        26,
        112,
        8,
        104,
        26,
        27,
        4,
        52,
        22,
        22,
        29,
        43,
        22,
        34,
        22,
        26,
        218,
        25,
        30,
        18,
        7,
        4,
        2,
        3,
        3,
        4,
        4,
        24,
        2,
        16,
        8,
        16,
        2,
        2,
        1,
        0,
    };
    return metrics;
}
