[thinknode_m9_base]
extends = esp32s3_base
board = crowpanel
board_check = true
board_build.partitions = default_16MB.csv
upload_protocol = esptool
build_src_filter =
  ${esp32s3_base.build_src_filter}
  +<../variants/esp32s3/ELECROW-ThinkNode-M9>
build_flags =
  ${esp32s3_base.build_flags}
  -I variants/esp32s3/ELECROW-ThinkNode-M9
  -D ELECROW_ThinkNode_M9
  -D BOARD_HAS_PSRAM
  -D HAS_SDCARD=1
  -D SDCARD_USE_SPI1
  -D SDCARD_USER_SPI_BEGIN
  -D HAS_SCREEN=1
;  -L variants/esp32s3/ELECROW-ThinkNode-M9/lib
;  -lqst
lib_deps = ${esp32s3_base.lib_deps}
  lovyan03/LovyanGFX@1.2.19
  lewisxhe/SensorLib@0.3.4

[env:thinknode_m9]
extends = thinknode_m9_base
build_flags = 
  ${thinknode_m9_base.build_flags}
  
[env:thinknode_m9-tft]
extends = thinknode_m9_base
build_flags = 
  ${thinknode_m9_base.build_flags}
  -D RADIOLIB_SPI_PARANOID=0
  -D CONFIG_DISABLE_HAL_LOCKS=1
  -D HAS_TFT=1
  -D USE_PACKET_API
  -D LV_LVGL_H_INCLUDE_SIMPLE
  -D LV_CONF_INCLUDE_SIMPLE
  -D LV_COMP_CONF_INCLUDE_SIMPLE
  -D LV_USE_SYSMON=0
  -D LV_USE_PROFILER=0
  -D LV_USE_PERF_MONITOR=0
  -D LV_USE_MEM_MONITOR=0
  -D LV_USE_LOG=0
  -D LV_BUILD_TEST=0
  -D USE_LOG_DEBUG
  -D LOG_DEBUG_INC=\"DebugConfiguration.h\"
  -D RAM_SIZE=5120
  -D LGFX_DRIVER_TEMPLATE
  -D LGFX_DRIVER=LGFX_GENERIC
  -D GFX_DRIVER_INC=\"graphics/LGFX/LGFX_GENERIC.h\"
  -D VIEW_320x240
  -D LGFX_PANEL=ST7789
  -D DISPLAY_SIZE=320x240
  -D LGFX_ROTATION=3
  -D LGFX_CFG_HOST=SPI3_HOST
  -D LGFX_PIN_SCK=40
  -D LGFX_PIN_MOSI=47
  -D LGFX_PIN_DC=15
  -D LGFX_PIN_CS=16
  -D LGFX_PIN_BL=17
  -D LGFX_PIN_RST=14
  -D LGFX_SCREEN_WIDTH=240
  -D LGFX_SCREEN_HEIGHT=320
  -D LGFX_INVERT_LIGHT=true
  -D SPI_FREQUENCY=80000000
  -D MAP_FULL_REDRAW

lib_deps = 
  ${thinknode_m9_base.lib_deps}
  ${device-ui_base.lib_deps}








  
