; First prototype nrf52840/sx1262 device
[env:heltec-mesh-node-t096]
extends = nrf52840_base
board = heltec_mesh_node_t096
board_level = pr
debug_tool = jlink

# add -DCFG_SYSVIEW if you want to use the Segger systemview tool for OS profiling.
build_flags = ${nrf52840_base.build_flags}
  -Ivariants/nrf52840/heltec_mesh_node_t096
  -D HAS_LORA_FEM=1
  -D HELTEC_MESH_NODE_T096
  -D USE_TFTDISPLAY=1
  -D USER_SETUP_LOADED
  -D ST7735_DRIVER      ; Define additional parameters below for this display
  -D ST7735_REDTAB160x80
  -D TFT_SPI_PORT=SPI1 
  -D TFT_CS=ST7735_CS  ; Chip select control pin D8
  -D TFT_DC=ST7735_RS  ; Data Command control pin
  -D TFT_RST=ST7735_RESET  ; Reset pin (could connect to NodeMCU RST, see next line)
  -D TFT_BL=ST7735_BL  ; LED back-light (only for ST7789 with backlight control pin)
  -D TFT_BACKLIGHT_ON=LOW
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/heltec_mesh_node_t096>
lib_deps = 
  ${nrf52840_base.lib_deps}
  bodmer/TFT_eSPI@2.5.43 ; renovate: datasource=platformio-registry depName=bodmer/TFT_eSPI
