[env:t-eth-elite]
extends = esp32s3_base
board = esp32s3box
board_level = pr
board_check = true
board_build.partitions = default_16MB.csv
build_flags = 
  ${esp32s3_base.build_flags}
  -D T_ETH_ELITE
  -D HAS_UDP_MULTICAST=1
  -I variants/esp32s3/t-eth-elite

custom_sdkconfig =
  ${esp32s3_base.custom_sdkconfig}
  CONFIG_ETH_ENABLED=y
  CONFIG_ARDUINO_SELECTIVE_Ethernet=y
