[env:dfr1195-diy]
extends = esp32s3_base
; board assumes the lowest spec WROOM module: 4 MB (Quad SPI) Flash, No PSRAM
board = ESP32-S3-WROOM-1-N4
board_level = extra
lib_deps =
  ${esp32s3_base.lib_deps}
  lovyan03/LovyanGFX@1.2.19
build_flags =
  ${esp32s3_base.build_flags}
  -D PRIVATE_HW
  -I variants/esp32s3/diy/dfr1195-diy
  -fno-lto
build_unflags =
  ${esp32s3_base.build_unflags}
  -flto