[env:nugget-s2-lora]
extends = esp32s2_base
board = lolin_s2_mini
board_level = extra
board_check = true
board_build.extra_flags =
  -DARDUINO_LOLIN_S2_MINI
  -DBOARD_HAS_PSRAM
  -DNUGGET_S2_LORA
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=0
build_flags =
  ${esp32s2_base.build_flags}
  -DNUGGET_S2_LORA
  -D PRIVATE_HW
  -include variants/esp32s2/nugget_s2_lora/tinyusb_compat.h
  -I${platformio.packages_dir}/framework-arduinoespressif32-libs/esp32s2/include/arduino_tinyusb/include
  -I${platformio.packages_dir}/framework-arduinoespressif32-libs/esp32s2/include/arduino_tinyusb/tinyusb/src
  -L${platformio.packages_dir}/framework-arduinoespressif32-libs/esp32s2/lib
  -larduino_tinyusb
  -I variants/esp32s2/nugget_s2_lora

extra_scripts =
  ${esp32s2_base.extra_scripts}
  variants/esp32s2/nugget_s2_lora/tinyusb_dummy.py

custom_sdkconfig =
  ${esp32s2_base.custom_sdkconfig}
  CONFIG_TINYUSB_ENABLED=y
  CONFIG_TINYUSB_CDC_ENABLED=y
  CONFIG_TINYUSB_CDC_MAX_PORTS=2
  CONFIG_TINYUSB_CDC_RX_BUFSIZE=64
  CONFIG_TINYUSB_CDC_TX_BUFSIZE=64
