#pragma once

#define CONFIG_TINYUSB_ENABLED 1
#define CONFIG_TINYUSB_CDC_ENABLED 1
#define CONFIG_TINYUSB_CDC_RX_BUFSIZE 64
#define CONFIG_TINYUSB_CDC_TX_BUFSIZE 64
#define CONFIG_TINYUSB_CDC_MAX_PORTS 2
