[env:t-mini-epaper-s3]
custom_meshtastic_hw_model = 16
custom_meshtastic_hw_model_slug = TLORA_T3_S3
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = LILYGO Mini Epaper S3
custom_meshtastic_tags = LilyGo
custom_meshtastic_requires_dfu = true

extends = esp32s3_base, inkhud
board = tlora-t3s3-v1
board_check = true
upload_protocol = esptool

build_src_filter =
  ${esp32s3_base.build_src_filter}
  ${inkhud.build_src_filter}
build_flags =
  ${esp32s3_base.build_flags}
  ${inkhud.build_flags}
  -I variants/esp32s3/t-mini-epaper-s3

lib_deps =
  ${inkhud.lib_deps} ; InkHUD libs first, so we get GFXRoot instead of AdafruitGFX
  ${esp32s3_base.lib_deps}
  # renovate: datasource=custom.pio depName=SensorLib packageName=lewisxhe/library/SensorLib
  lewisxhe/SensorLib@0.3.4

[env:t-mini-epaper-s3-inkhud]
extends = env:t-mini-epaper-s3
