; Russell is a board designed to mount on an ER34615/IFR32700 cell and go Up! on a balloon
; Hardware repository: https://github.com/Meshtastic-Malaysia/russell
; - RAK3172 STM32WLE5CCU6 MCU + integrated SX1262 LoRa
; - CDtop CD-PA1010D GPS
; - Bosch Sensortec BME280 sensor
; - Consonance CN3158 LiFePO4 solar charger
[env:russell]
extends = stm32_base
board = wiscore_rak3172
board_level = extra
board_upload.maximum_size = 247808 ; reserve the last 14KB for filesystem (reduced from 20KB in LittleFS.cpp)
build_flags =
  ${stm32_base.build_flags}
  -Ivariants/stm32/russell
  -DPRIVATE_HW
  -DMESHTASTIC_EXCLUDE_AIR_QUALITY_SENSOR=1
  -DMESHTASTIC_EXCLUDE_RANGETEST=1
  -DMESHTASTIC_EXCLUDE_DETECTIONSENSOR=1
  -DMESHTASTIC_EXCLUDE_EXTERNALNOTIFICATION=1
  -DMESHTASTIC_EXCLUDE_POWERSTRESS=1
  -DMESHTASTIC_EXCLUDE_NEIGHBORINFO=1
  -DMESHTASTIC_EXCLUDE_TRACEROUTE=1
  -DMESHTASTIC_EXCLUDE_WAYPOINT=1
lib_deps =
  ${stm32_base.lib_deps}
	# renovate: datasource=custom.pio depName=Adafruit BME280 packageName=adafruit/library/Adafruit BME280 Library
	adafruit/Adafruit BME280 Library@2.3.0
	# renovate: datasource=custom.pio depName=Adafruit_BME680 packageName=adafruit/library/Adafruit BME680 Library
	adafruit/Adafruit BME680 Library@2.0.6

upload_port = stlink
