[env:polysafe-t1000e]
extends = env:tracker-t1000-e
build_flags =
    ${env:tracker-t1000-e.build_flags}
    -D POLYSAFE=1
    -D POLYSAFE_TRACKER=1
    -D POLYSAFE_DEVICE_T1000E=1
    -I src/polysafe

[env:polysafe-wio-l1]
extends = env:seeed_wio_tracker_L1
build_flags =
    ${env:seeed_wio_tracker_L1.build_flags}
    -D POLYSAFE=1
    -D POLYSAFE_SCREEN_RECEIVER=1
    -D POLYSAFE_DEVICE_WIO_L1=1
    -I src/polysafe