; Meshtastic DIY v1.1 ESP32-S3-Zero + E22-900M30S
[env:esp32s3-zero-v1_1]
extends = esp32s3_base
board = esp32-s3-zero
board_level = extra
;board_check = true
board_upload.flash_size = 4MB
upload_speed = 921600
monitor_speed = 115200
build_flags =
  ${esp32_base.build_flags}
  -DBOARD_HAS_PSRAM
  -D DIY_V1
;  -D EBYTE_E22
  -I variants/esp32/diy/esp32s3_zero_v1_1
