[env:arduino-nesso-n1]
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = ARDUINO_NESSO_N1
custom_meshtastic_architecture = esp32-c6
custom_meshtastic_actively_supported = false
custom_meshtastic_display_name = Arduino Nesso N1
custom_meshtastic_tags = DIY

extends = esp32c6_base
board = esp32-c6-devkitc-1
board_level = extra
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
;OpenOCD flash method
;upload_protocol = esp-builtin
;Normal method
upload_protocol = esptool
;upload_port = /dev/ttyACM2
build_flags = 
  ${esp32c6_base.build_flags}
  -D PRIVATE_HW
  -D ARDUINO_NESSO_N1
  -D M5STACK_UNITC6L
  -I variants/esp32c6/arduino_nesso_n1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
monitor_speed=115200
build_src_filter = 
 ${esp32c6_base.build_src_filter} +<../variants/esp32c6/arduino_nesso_n1>
lib_deps =
  ${esp32c6_base.lib_deps}
  # renovate: datasource=custom.pio depName=LovyanGFX packageName=lovyan03/library/LovyanGFX
  lovyan03/LovyanGFX@1.2.21
  https://github.com/mverch67/BQ27220/archive/07d92be846abd8a0258a50c23198dac0858b22ed.zip
