; ESP32 C3 Super Mini Development Board
; https://www.espboards.dev/esp32/esp32-c3-super-mini/
[env:esp32c3_moonshine_mv]

extends = esp32c3_base
board = esp32-c3-devkitm-1
board_level = pr
build_flags = 
  ${esp32c3_base.build_flags}
  -D PRIVATE_HW
  -I variants/esp32c3/diy/esp32c3_moonshine_mv
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
upload_protocol = esptool
;upload_port = /dev/ttyUSB0
upload_speed = 921600


; ------------------- Flash 核心配置 -------------------
; 1. Flash 容量（根据硬件实际值改，常见 4MB/8MB）
board_build.flash_size = 4MB
; 2. Flash 模式（ESP32-C3 推荐 dio）
board_build.flash_mode = dio
; 3. Flash 时钟频率（ESP32-C3 推荐 80MHz）
board_build.flash_freq = 80MHz

; （可选）上传时的 Flash 配置（和上面保持一致即可）
board_upload.flash_size = 4MB
