; LightTracker Plus : ESP32-S3 + EBYTE E22-400M30S
; https://shop.qrp-labs.com/aprs/lighttrackerplus
[env:QRPLabs_LightTracker_Plus_1_0]
extends = esp32s3_base
board = esp32-s3-devkitc-1
board_level = diy
board_check = true
board_build.partitions = default_8MB.csv
extra_scripts = 
  pre:bin/platformio-pre.py
  bin/platformio-custom.py
build_flags =
  ${esp32s3_base.build_flags}
  -D LightTracker_Plus_1_0
  -D EBYTE_E22
  -D EBYTE_E22_400M30S ; Assume Tx power curve is identical to 900M30S as there is no documentation
  -I variants/esp32s3/diy/QRPLabs_LightTracker_Plus_1_0
lib_deps = 
  ${esp32s3_base.lib_deps}
