; M5stack Cardputer Advanced
[env:m5stack-cardputer-adv]
extends = esp32s3_base
board = m5stack-stamps3
board_check = true
board_build.partitions = default_8MB.csv
upload_protocol = esptool
build_flags = 
  ${esp32s3_base.build_flags}
  -D M5STACK_CARDPUTER_ADV
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -I variants/esp32s3/m5stack_cardputer_adv
build_src_filter =
  ${esp32s3_base.build_src_filter}
  +<../variants/esp32s3/m5stack_cardputer_adv>
lib_deps =
  ${esp32s3_base.lib_deps}
  # renovate: datasource=git-refs depName=meshtastic-st7789 packageName=https://github.com/meshtastic/st7789 gitBranch=main
  https://github.com/meshtastic/st7789/archive/7228c498001481a444e157413e1ea517dd6f436a.zip
  # renovate: datasource=github-tags depName=pschatzmann_arduino-audio-driver packageName=pschatzmann/arduino-audio-driver
  https://github.com/pschatzmann/arduino-audio-driver/archive/v0.2.1.zip
  # renovate: datasource=git-refs depName=ESP8266Audio packageName=https://github.com/meshtastic/ESP8266Audio gitBranch=meshtastic-2.0.0-dacfix
  https://github.com/meshtastic/ESP8266Audio/archive/343024632ee78d6216907b2353fc943a62422d80.zip
  # renovate: datasource=custom.pio depName=ESP8266SAM packageName=earlephilhower/library/ESP8266SAM
  earlephilhower/ESP8266SAM@1.1.0
  # renovate: datasource=custom.pio depName=NeoPixel packageName=adafruit/library/Adafruit NeoPixel
  adafruit/Adafruit NeoPixel@1.15.4
