[env:makerpython_nrf52840_sx1280_eink]
board_level = extra
extends = nrf52840_base, niche
board = nordic_pca10059
build_flags = ${nrf52840_base.build_flags}
  ${niche.build_flags}
  -Ivariants/nrf52840/MakePython_nRF52840_eink
  -D PRIVATE_HW
  -D PIN_EINK_EN
build_src_filter = ${nrf52_base.build_src_filter} ${niche.build_src_filter} +<../variants/nrf52840/MakePython_nRF52840_eink>
lib_deps =
  ${nrf52840_base.lib_deps}
  # renovate: datasource=git-refs depName=meshtastic-ESP32_Codec2 packageName=https://github.com/meshtastic/ESP32_Codec2 gitBranch=master
  https://github.com/meshtastic/ESP32_Codec2/archive/633326c78ac251c059ab3a8c430fcdf25b41672f.zip
debug_tool = jlink
;upload_port = /dev/ttyACM4