[env:mappi32]
custom_meshtastic_hw_model = 99
custom_meshtastic_hw_model_slug = MAPPi32
custom_meshtastic_architecture = esp32
custom_meshtastic_actively_supported = true
custom_meshtastic_display_name = Mappi32
custom_meshtastic_tags = KMTECH

board_level = extra
extends = esp32_base
board = esp32dev

build_flags =
  ${esp32_base.build_flags}
  -D MAPPi32
  -I variants/esp32/mappi32
  -ULED_BUILTIN

monitor_speed = 115200
upload_protocol = esptool
upload_speed = 921600
;upload_port = /dev/ttyUSB0