; Big Visualizer - ESP32-S3-DevKitC-1 (N16R8) + 128x64 HUB75 matrix + Wio-SX1262 - DIY
[env:visualizer-hub75]
extends = esp32s3_base
board = esp32-s3-devkitc-1
board_check = true
board_build.partitions = default_16MB.csv
board_level = extra
board_upload.flash_size = 16MB          ; N16R8 -> 16MB flash
board_build.arduino.memory_type = qio_opi ; N16R8 -> 8MB octal (OPI) PSRAM
build_flags =
  ${esp32s3_base.build_flags}
  -D VISUALIZER_HUB75
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -I variants/esp32s3/visualizer-hub75
lib_deps =
  ${esp32s3_base.lib_deps}
  # renovate: datasource=github-tags depName=ESP32-HUB75-MatrixPanel-I2S-DMA packageName=mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA
  https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/archive/refs/tags/3.0.14.zip
