[env:waveshark-radio]
extends = esp32_base
board = waveshark-radio
board_level = extra

custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = PRIVATE_HW
custom_meshtastic_architecture = esp32
custom_meshtastic_actively_supported = false
custom_meshtastic_display_name = WaveShark Radio
custom_meshtastic_tags = WaveShark
custom_meshtastic_url = https://www.waveshark.net/

build_flags =
  ${esp32_base.build_flags}
  -D PRIVATE_HW
  -D WAVESHARK_RADIO
  -D USERPREFS_CONFIG_LORA_REGION=meshtastic_Config_LoRaConfig_RegionCode_US
  -I variants/esp32/waveshark-radio
  -ULED_BUILTIN
