; Hackaday Communicator
[env:hackaday-communicator]
extends = esp32s3_base
board = hackaday-communicator
board_check = true
board_build.partitions = default_16MB.csv
upload_protocol = esptool

build_src_filter =
  ${esp32s3_base.build_src_filter}
  +<../variants/esp32s3/hackaday-communicator>

build_flags = ${esp32s3_base.build_flags} 
  -D HACKADAY_COMMUNICATOR
  -D BOARD_HAS_PSRAM
  -I variants/esp32s3/hackaday-communicator

lib_deps = ${esp32s3_base.lib_deps}
  # renovate: datasource=git-refs depName=moononournation-Arduino_GFX packageName=https://github.com/moononournation/Arduino_GFX gitBranch=master
  https://github.com/moononournation/Arduino_GFX/archive/refs/tags/v1.6.5.zip