[inkhud]
build_src_filter =
  +<graphics/niche/>; Include the nicheGraphics directory
  -<graphics/draw/> ; BaseUI renderer stack is disabled for InkHUD
  -<graphics/fonts/> ; InkHUD uses GFX_Root fonts instead of BaseUI font tables
  -<graphics/EInkDisplay2.cpp> ; InkHUD drives e-ink through niche drivers
  -<graphics/EInkDynamicDisplay.cpp>
  -<graphics/EInkParallelDisplay.cpp>
  -<graphics/EmoteRenderer.cpp>
  -<graphics/emotes.cpp>
  -<graphics/Panel_sdl.cpp>
  -<graphics/ScreenGlobals.cpp>
  -<graphics/SharedUIDisplay.cpp>
  -<graphics/TFTColorRegions.cpp>
  -<graphics/TFTDisplay.cpp>
  -<graphics/tftSetup.cpp>
  -<graphics/TimeFormatters.cpp>
  -<graphics/VirtualKeyboard.cpp>
build_flags =
  -D MESHTASTIC_INCLUDE_NICHE_GRAPHICS ; Use NicheGraphics
  -D MESHTASTIC_INCLUDE_INKHUD ; Use InkHUD (a NicheGraphics UI)
  -D MESHTASTIC_EXCLUDE_SCREEN ; Suppress default Screen class
  -D MESHTASTIC_EXCLUDE_INPUTBROKER ; Suppress default input handling
  -D HAS_BUTTON=0 ; Suppress default ButtonThread
lib_deps =
  # renovate: datasource=github-tags depName=GFX_Root packageName=ZinggJM/GFX_Root
  https://github.com/ZinggJM/GFX_Root/archive/3195764e352a0d2567c8d277ac408ca7293a99b0.zip ; Used by InkHUD as a "slimmer" version of AdafruitGFX
