[env:meshnology_w10]
custom_meshtastic_hw_model = 140
custom_meshtastic_hw_model_slug = MESHNOLOGY_W10
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = Meshnology W10
custom_meshtastic_requires_dfu = true
custom_meshtastic_partition_scheme = 16MB

; ESP32-S3R8: 8 MB OPI PSRAM, W25Q128JVSIQ = 16 MB QIO flash (pg1)
board = esp32-s3-devkitc-1
board_level = pr
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi

extends = esp32s3_base
build_flags =
  ${esp32s3_base.build_flags}
  -D MESHNOLOGY_W10
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -I variants/esp32s3/meshnology-w10

lib_deps =
  ${esp32s3_base.lib_deps}
  ; ST7789/ST7796 TFT (USE_TFTDISPLAY)
  ; renovate: datasource=custom.pio depName=LovyanGFX packageName=lovyan03/library/LovyanGFX
  lovyan03/LovyanGFX@1.2.21
  ; PCF85063 RTC driver (PCF85063_RTC)
  ; renovate: datasource=custom.pio depName=SensorLib packageName=lewisxhe/library/SensorLib
  lewisxhe/SensorLib@0.3.4
  ; ES8311 audio codec + I2S notification tones (HAS_I2S)
  ; renovate: datasource=github-tags depName=pschatzmann_arduino-audio-driver packageName=pschatzmann/arduino-audio-driver
  https://github.com/pschatzmann/arduino-audio-driver/archive/v0.3.0.zip
  # renovate: datasource=git-refs depName=ESP8266Audio packageName=https://github.com/meshtastic/ESP8266Audio gitBranch=meshtastic-2.0.0-dacfix
  https://github.com/meshtastic/ESP8266Audio/archive/343024632ee78d6216907b2353fc943a62422d80.zip
  # renovate: datasource=custom.pio depName=ESP8266SAM packageName=earlephilhower/library/ESP8266SAM
  earlephilhower/ESP8266SAM@1.1.0
