// Auto-generated by trie_static_generator.py from pinyin_sample.txt
#ifndef PINYIN_TRIE_EXCLUDE_H
#define PINYIN_TRIE_EXCLUDE_H

#include <cstddef>
#include <cstdint>
#include <cstring>

#define WORDS_MAX_WEIGHT_SIZE 11

// 9 unique pinyin tokens
static const char *PINYIN_TOKENS[] = {
    "ce", "guo", "hao", "jie", "lu", "ni", "shi", "zhong", "zuo",
};

// unique token initials (single lowercase letter)
static const char PINYIN_INITIALS[] = {
    'c', 'g', 'h', 'j', 'l', 'n', 's', 'z',
};

// mapping from initial index -> flat token id list (indices into PINYIN_TOKENS)
static const uint16_t INITIAL_TOKEN_IDS[] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8,
};

static const uint32_t INITIAL_TOKEN_RANGE[][2] = {
    {0, 1}, {1, 1}, {2, 1}, {3, 1}, {4, 1}, {5, 1}, {6, 1}, {7, 2},
};

// Node edges: for each node, a range into NODE_EDGES (start,count)
static const uint16_t NODE_EDGE_COUNT = 10;
struct Edge {
    uint16_t token_id;
    uint16_t child_node;
};
static const Edge NODE_EDGES[] = {
    {0, 1}, {5, 3}, {6, 5}, {7, 7}, {8, 9}, {6, 2}, {2, 4}, {3, 6}, {1, 8}, {4, 10},
};

static const uint32_t NODE_EDGE_RANGE[][2] = {
    {0, 5}, {5, 1}, {6, 0}, {6, 1}, {7, 0}, {7, 1}, {8, 0}, {8, 1}, {9, 0}, {9, 1}, {10, 0},
};

// Words pool: 5 entries (string pool + offsets + weights)
static const unsigned char WORDS_DATA[] = {
    230, 181, 139, 232, 175, 149, 0,   228, 189, 160, 229, 165, 189, 0,   228, 184, 150, 231,
    149, 140, 0,   228, 184, 173, 229, 155, 189, 0,   229, 183, 166, 232, 183, 175, 0,
};

static const uint32_t WORDS_OFFSETS[] = {
    0, 7, 14, 21, 28,
};

static const uint32_t WORDS_MAX_WEIGHT[] = {
    1200, 500, 500, 1000, 1000, 900, 900, 1200, 1200, 350, 350,
};

static const int32_t WORDS_WEIGHT[] = {
    500, 1000, 900, 1200, 350,
};

// character counts for each WORDS entry (number of Chinese characters)
static const uint8_t WORD_CHAR_COUNT[] = {
    2, 2, 2, 2, 2,
};

static const uint32_t NODE_WORD_RANGE[][2] = {
    {0, 0}, {0, 0}, {0, 1}, {1, 0}, {1, 1}, {2, 0}, {2, 1}, {3, 0}, {3, 1}, {4, 0}, {4, 1},
};

#endif // PINYIN_TRIE_EXCLUDE_H
