; Edict HP - Delta family nRF52840 variant
[env:edict_hp]
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = DELTA_HP
custom_meshtastic_architecture = nrf52840
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = Edict HP
custom_meshtastic_images = edict_hp.svg, edict_hp_case.svg
custom_meshtastic_tags = Edict, Delta

extends = nrf52840_base
board = delta_hp
board_level = pr
board_check = true
build_type = release
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/edict_hp
  -D DELTA_HP
  -D EDICT_HP
  -DMESHTASTIC_USE_EINK_UI=0
  -DMESHTASTIC_EXCLUDE_SCREEN=1
  -DMESHTASTIC_EXCLUDE_GPS=1
  -DMESHTASTIC_EXCLUDE_I2C=1
  -DMESHTASTIC_EXCLUDE_DETECTIONSENSOR=1
  -DMESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR=1
  -DMESHTASTIC_EXCLUDE_AIR_QUALITY_SENSOR=1
  -DMESHTASTIC_EXCLUDE_INPUTBROKER=1
  -DMESHTASTIC_EXCLUDE_MQTT=1
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
  -DRADIOLIB_EXCLUDE_LR2021=1
build_src_filter = ${nrf52_base.build_src_filter} \
  +<../variants/nrf52840/edict_hp> \
  -<graphics/EInkDisplay2.cpp> \
  -<graphics/EInkDynamicDisplay.cpp> \
  -<graphics/fonts/EinkDisplayFonts.cpp>
lib_deps =
  ${nrf52840_base.lib_deps}

; If not set we will default to uploading over serial (first it forces bootloader entry by talking 1200bps to cdcacm)
; Note: as of 6/2013 the serial/bootloader based programming takes approximately 30 seconds
;upload_protocol = jlink

; Allows programming and debug via a CMSIS-DAP / STLink debugger
; programming time is about the same as the bootloader version.
; For information on this see the meshtastic developers documentation for "Development on the NRF52"
[env:edict_hp_dbg]
extends = env:edict_hp
board_level = extra

; if the builtin version of openocd has a buggy version of semihosting, so use the external version
; platform_packages = platformio/tool-openocd@3.1200.0

build_flags =
  ${env:edict_hp.build_flags}
  -D USE_SEMIHOSTING

lib_deps =
  ${env:edict_hp.lib_deps}
  # TODO renovate
  https://github.com/geeksville/Armduino-Semihosting/archive/35b538fdf208c3530c1434cd099a08e486672ee4.zip

; NOTE: the pyocd support for semihosting is buggy.  So I switched to using the builtin platformio support for the stlink adapter which worked much better.
; However the built in openocd version in platformio has buggy support for TCP to semihosting.
;
; So I'm now trying the external openocd - but the openocd scripts for nrf52.cfg assume you are using a DAP adapter not an STLINK adapter.
; In theory I could change those scripts.  But for now I'm trying going back to a DAP adapter but with the external openocd.

upload_protocol = stlink
; eventually use platformio/tool-pyocd@2.3600.0 instad
;upload_protocol = custom
;upload_command = pyocd flash -t nrf52840 $UPLOADERFLAGS $SOURCE
