[nrf54l15_base]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
framework = zephyr
extends = arduino_base

build_type = release
build_flags =
  ${arduino_base.build_flags}
  -Isrc/platform/nrf54l15
  -DMESHTASTIC_EXCLUDE_AUDIO=1
  -DMESHTASTIC_EXCLUDE_GPS=1
  -DMESHTASTIC_EXCLUDE_MQTT=1
  -DHAS_WIRE=0
  -DHAS_SENSOR=0
  -DHAS_BUTTON=0
  -DHAS_TELEMETRY=0
  -DMESHTASTIC_EXCLUDE_PAXCOUNTER=1
  -DARDUINO=100
  -DMESHTASTIC_EXCLUDE_ACCELEROMETER=1
  -DMAX_NUM_NODES=40
  -fpermissive
  # Libraries that Zephyr LDF misses; add include paths explicitly
  -I.pio/libdeps/nrf54l15dk/Crypto
  -I.pio/libdeps/nrf54l15dk/ArduinoThread
  -I".pio/libdeps/nrf54l15dk/ESP8266 and ESP32 OLED driver for SSD1306 displays/src"
  -I.pio/libdeps/nrf54l15dk/OneButton/src
  -I.pio/libdeps/nrf54l15dk/arduino-fsm
  -I.pio/libdeps/nrf54l15dk/TinyGPSPlus/src
  -I.pio/libdeps/nrf54l15dk/ErriezCRC32/src
  -I.pio/libdeps/nrf54l15dk/NonBlockingRTTTL/src
  -I.pio/libdeps/nrf54l15dk/RadioLib/src

build_src_filter =
  ${arduino_base.build_src_filter}
  -<platform/esp32/>
  -<platform/stm32wl>
  -<platform/nrf52/>
  -<platform/rp2xx0>
  -<nimble/>
  -<mesh/wifi/>
  -<mesh/api/>
  -<mesh/http/>
  -<modules/esp32>
  -<mesh/eth/>
  -<mesh/raspihttp>
  -<serialization/>
  -<mqtt/>
  -<motion/>
  +<platform/nrf54l15/>

lib_compat_mode = off

lib_deps =
  ${arduino_base.lib_deps}
  ${radiolib_base.lib_deps}
  rweather/Crypto@0.4.0

lib_ignore =
  BluetoothOTA
  lvgl
  Adafruit_nRFCrypto
