[env:tracker-t1000-e-pro]
custom_meshtastic_support_level = 1
custom_meshtastic_images = tracker-t1000-e-pro.svg
custom_meshtastic_tags = Seeed

extends = nrf52840_base
board = tracker-t1000-e-pro
board_level = pr
custom_meshtastic_hw_model = 71
custom_meshtastic_hw_model_slug = TRACKER_T1000_E_PRO
custom_meshtastic_architecture = nrf52840
custom_meshtastic_display_name = Seeed SenseCAP T1000-E-Pro
custom_meshtastic_actively_supported = true
build_flags = ${nrf52840_base.build_flags}
  -Ivariants/nrf52840/tracker-t1000-e-pro
  -Isrc/platform/nrf52/softdevice
  -Isrc/platform/nrf52/softdevice/nrf52
  -DTRACKER_T1000_E_PRO
  -DCONFIG_NFCT_PINS_AS_GPIOS=1
  -DMESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR_EXTERNAL=1
  -DMESHTASTIC_EXCLUDE_CANNEDMESSAGES=1
  -DMESHTASTIC_EXCLUDE_SCREEN=1
  -DMESHTASTIC_EXCLUDE_DETECTIONSENSOR=1
  -DMESHTASTIC_EXCLUDE_WIFI=1
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/tracker-t1000-e-pro>
lib_deps = 
  ${nrf52840_base.lib_deps}
  adafruit/Adafruit DRV2605 Library@1.2.4

debug_tool = jlink
; If not set we will default to uploading over serial (first it forces bootloader entry by talking 1200bps to cdcacm)
upload_protocol = nrfutil
