[tinylora_base]
lib_deps =
  ${esp32c3_base.lib_deps}
  adafruit/Adafruit NeoPixel @ ^1.12.0

[env:tinylora_v2_22s]
extends = esp32c3_base
board_meshcn = true
board = esp32-c3-devkitm-1
lib_deps = ${tinylora_base.lib_deps}
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V2
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:tinylora_v2_29s]
extends = esp32c3_base
board_meshcn = true
board = esp32-c3-devkitm-1
lib_deps = ${tinylora_base.lib_deps}
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V2
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D SX126X_MAX_POWER=3

[env:tinylora_v3_gps_29s]
extends = esp32c3_base
board_meshcn = true
board = esp32-c3-devkitm-1
lib_deps = ${tinylora_base.lib_deps}
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V3
  -D TINYLORA_V3_GPS
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D SX126X_MAX_POWER=3

[env:tinylora_v3_gps_22s]
extends = esp32c3_base
board_meshcn = true
board = esp32-c3-devkitm-1
lib_deps = ${tinylora_base.lib_deps}
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V3
  -D TINYLORA_V3_GPS
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D SX126X_MAX_POWER=22

[env:tinylora_v3_i2c_29s]
extends = esp32c3_base
board_meshcn = true
board = esp32-c3-devkitm-1
lib_deps = ${tinylora_base.lib_deps}
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V3
  -D TINYLORA_V3_I2C
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D SX126X_MAX_POWER=3

[env:tinylora_v3_i2c_22s]
extends = esp32c3_base
board_meshcn = true
board = esp32-c3-devkitm-1
lib_deps = ${tinylora_base.lib_deps}
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V3
  -D TINYLORA_V3_I2C
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D SX126X_MAX_POWER=22

[env:tinylora_v4v5]
extends = esp32c3_base
board_meshcn = true
board = esp32-c3-devkitm-1
lib_deps = ${tinylora_base.lib_deps}
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V4
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:tinylora_mv]
extends = esp32c3_base
board_level = pr
board_meshcn = true
board = tinylora
board_build.flash_mode = dio
board_build.arduino.memory_type = dio_qspi
board_build.partitions = variants/esp32c3/tinylora/tinylora_mv-8M.csv
lib_deps = ${tinylora_base.lib_deps}
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA
  -D TINYLORA_MV
  -D TINYLORA_ADVANCED_IME
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:tinylora_mv_zhcn]
extends = esp32c3_base
board_level = pr
board_meshcn = true
board = tinylora
board_build.flash_mode = dio
board_build.arduino.memory_type = dio_qspi
board_build.partitions = variants/esp32c3/tinylora/tinylora_mv-8M.csv
lib_deps = ${tinylora_base.lib_deps}
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA
  -D TINYLORA_MV
  -D TINYLORA_ADVANCED_IME
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D UI_LANG_ZH_CN
  -D OLED_CJK=1
  -D OLED_CJK_SIZE=10
  -D OLEDDISPLAY_UTF8_TOP_PADDING=2
