; ST Nucleo-WL55JC dev board
; https://www.st.com/en/evaluation-tools/nucleo-wl55jc.html
[env:nucleo_wl55jc]
extends = stm32_base
board = nucleo_wl55jc
board_level = extra
board_upload.maximum_size = 247808 ; reserve the last 14KB for filesystem
build_flags =
  ${stm32_base.build_flags}
  -Ivariants/stm32/nucleo_wl55jc
  -DPRIVATE_HW
  -DENABLE_HWSERIAL2
  -DHAS_GPS=1
  -DGPS_SERIAL_PORT=Serial2 ; Default Serial object is used for onboard ST-Link VCP
  -DHAS_SENSOR=1
lib_deps =
  ${stm32_base.lib_deps}
  # renovate: datasource=github-tags depName=STM32RTC packageName=stm32duino/STM32RTC
  https://github.com/stm32duino/STM32RTC/archive/refs/tags/1.9.0.zip
  # renovate: datasource=github-tags depName=STM32LowPower packageName=stm32duino/STM32LowPower
  https://github.com/stm32duino/STM32LowPower/archive/refs/tags/1.5.0.zip

upload_port = stlink
