; First prototype eink/nrf52840/sx1262 device
[env:thinknode_m1]
custom_meshtastic_hw_model = 89
custom_meshtastic_hw_model_slug = THINKNODE_M1
custom_meshtastic_architecture = nrf52840
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = ThinkNode M1
custom_meshtastic_images = thinknode_m1.svg
custom_meshtastic_tags = Elecrow
custom_meshtastic_has_ink_hud = true

extends = nrf52840_base, niche
board = ThinkNode-M1
board_check = true
debug_tool = jlink

build_flags = ${nrf52840_base.build_flags}
  ${niche.build_flags}
  -Ivariants/nrf52840/ELECROW-ThinkNode-M1
  -DELECROW_ThinkNode_M1
  -DUSE_EINK

build_src_filter = ${nrf52_base.build_src_filter} ${niche.build_src_filter} +<../variants/nrf52840/ELECROW-ThinkNode-M1>
lib_deps =
  ${nrf52840_base.lib_deps}
  # renovate: datasource=custom.pio depName=nRF52_PWM packageName=khoih-prog/library/nRF52_PWM
  khoih-prog/nRF52_PWM@1.0.1
;upload_protocol = fs

[env:thinknode_m1-inkhud]
extends = nrf52840_base, inkhud
board = ThinkNode-M1
board_check = true
debug_tool = jlink
build_flags =
  ${nrf52840_base.build_flags}
  ${inkhud.build_flags}
  -I variants/nrf52840/ELECROW-ThinkNode-M1
  -D ELECROW_ThinkNode_M1
build_src_filter =
  ${nrf52_base.build_src_filter}
  ${inkhud.build_src_filter}
  +<../variants/nrf52840/ELECROW-ThinkNode-M1>
lib_deps =
  ${inkhud.lib_deps} ; InkHUD libs first, so we get GFXRoot instead of AdafruitGFX
  ${nrf52840_base.lib_deps}
