[env:qltp]
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = QRP_LIGHTTRACKER_PLUS
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 0
custom_meshtastic_display_name = QRP LightTracker Plus
custom_meshtastic_partition_scheme = 8MB

extends = esp32s3_base
board = esp32-s3-devkitc-1
board_level = diy
board_check = true
board_build.partitions = default_8MB.csv
extra_scripts = 
  pre:fix_shell.py
  pre:bin/platformio-pre.py
  bin/platformio-custom.py

build_flags = 
  ${esp32s3_base.build_flags}
  -D LIGHTTRACKER_PLUS_1_0
  -I variants/esp32s3/qrp-lighttracker-plus
