/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "mesh.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Position, Position, AUTO)


PB_BIND(Data, Data, AUTO)


PB_BIND(User, User, AUTO)


PB_BIND(RouteDiscovery, RouteDiscovery, AUTO)


PB_BIND(SubPacket, SubPacket, 2)


PB_BIND(MeshPacket, MeshPacket, 2)


PB_BIND(ChannelSettings, ChannelSettings, AUTO)


PB_BIND(RadioConfig, RadioConfig, AUTO)


PB_BIND(RadioConfig_UserPreferences, RadioConfig_UserPreferences, 2)


PB_BIND(NodeInfo, NodeInfo, AUTO)


PB_BIND(MyNodeInfo, MyNodeInfo, AUTO)


PB_BIND(DeviceState, DeviceState, 2)


PB_BIND(DebugString, DebugString, 2)


PB_BIND(FromRadio, FromRadio, 2)


PB_BIND(ToRadio, ToRadio, 2)


PB_BIND(ManufacturingData, ManufacturingData, AUTO)







