; Hydra E22P - Enables support for the Ebyte E22P-868M30S and E22P-915M30S modules.
; WARNING: Do not flash this variant on a standard E22 Hydra, as it will result in hardware damage!
[env:hydra-e22p]
custom_meshtastic_hw_model = 39
custom_meshtastic_hw_model_slug = HYDRA
custom_meshtastic_architecture = esp32
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = Hydra-E22P
custom_meshtastic_tags = DIY

extends = esp32_base
board = esp32doit-devkit-v1
build_flags =
  ${esp32_base.build_flags}
  -D DIY_V1
  ;-DBOARD_HAS_PSRAM ; If a Wrover or Wroom module with a soldered PSRAM chip is used, the ESP32 will support up to 4 MB of memory.
  ;-D MAX_NUM_NODES=1000 ; I tested a PSRAM equipped node with allocated space for 10,000 (!) entries in the node database for several weeks without any problems.
  -I variants/esp32/diy/hydra-e22p
  -ULED_BUILTIN
