; The very slick RAK wireless RAK 4631 / 4630 board - Unified firmware for 5005/19003, with or without OLED RAK 1921
[env:gat562_mesh_trial_tracker]
extends = nrf52840_base
board_level = extra
board = gat562_mesh_trial_tracker
board_check = true
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/gat562_mesh_trial_tracker
  -D GAT562
  -D PRIVATE_HW
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
  -DRADIOLIB_EXCLUDE_LR2021=1
  -DMESHTASTIC_EXCLUDE_MAGNETOMETER=1
  -DMESHTASTIC_EXCLUDE_ACCELEROMETER=1
  -DGPS_POWER_TOGGLE
  -DADC_MULTIPLIER=1.73
  -DHAS_TRACKBALL=1
  -DTB_UP=28
  -DTB_DOWN=4
  -DTB_LEFT=30
  -DTB_RIGHT=31
  -DTB_PRESS=26
  -DTB_DIRECTION=FALLING
  -DPIN_BUZZER=33
  -DGAT562_NOTIFY_NEOPIXEL_PIN=29
  -DOLED_CJK=1
  -DOLED_CJK_CUSTOM=\"gat562_utf8_10x10.h\"
  -DOLED_CJK_SIZE=10
  -DOLEDDISPLAY_UTF8_TOP_PADDING=2
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/gat562_mesh_trial_tracker>
lib_deps =
  ${nrf52_base.lib_deps}
  https://github.com/adafruit/Adafruit_NeoPixel/archive/1.15.5.zip
  https://github.com/Kongduino/Adafruit_nRFCrypto/archive/8cde7189b5ead9dcd49f72601b43b969c0bbc06e.zip
  https://github.com/ssp97/pinyin_simple_backend/archive/5c945d338468ecaba287ba27848d9130c01fda66.zip
lib_ignore =
  ESP8266 and ESP32 OLED driver for SSD1306 displays
