; GAT562 T9: official Meshtastic core plus isolated TCA8418 input support.
[env:gat562_t9]
extends = nrf52840_base
board_level = extra
board = gat562_t9
board_check = true
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/gat562_mesh_trial_tracker
  -DGAT562_MESH_TRIAL_TRACKER
  -DGAT562
  -DPRIVATE_HW
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
  -DRADIOLIB_EXCLUDE_LR2021=1
  -DMESHTASTIC_EXCLUDE_MAGNETOMETER=1
  -DMESHTASTIC_EXCLUDE_ACCELEROMETER=1
  -DGAT562_DISABLE_EXTERNAL_FLASH=1
  -DHAS_BUTTON=1
  -DBUTTON_PIN=PIN_BUTTON1
  -DGAT562_DISABLE_DEFAULT_ALT_BUTTON=1
  -DGAT562_T9_KEYBOARD=1
  -DGAT562_T9_INT_PIN=20
  -DGAT562_T9_RST_PIN=19
  -DGAT562_DEL_PIN=21
  -DHAS_TRACKBALL=1
  -DTB_UP=28
  -DTB_DOWN=4
  -DTB_LEFT=30
  -DTB_RIGHT=31
  -DTB_PRESS=26
  -DTB_DIRECTION=FALLING
  -DDEBUG_MUTE
  -DPIN_BUZZER=33
  -DNEOPIXEL_STATUS_NOTIFICATION_PIN=29
  -DNEOPIXEL_STATUS_NOTIFICATION_COLOR=0xFFFFFF
  -DHAS_SENSOR=1
  -DUSERPREFS_CONFIG_ENVIRONMENT_MEASUREMENT_ENABLED=1
  -DUSERPREFS_CONFIG_ENV_SCREEN_SCREEN_ENABLED=1
  -DUSERPREFS_CONFIG_ENV_TELEM_UPDATE_INTERVAL=3600
  -DENVIRONMENTAL_TELEMETRY_MODULE_ENABLE=1
  -DOLED_CJK=1
  -DOLED_CJK_CUSTOM=\"gat562_utf8_10x10.h\"
  -DOLED_CJK_SIZE=10
  -DOLEDDISPLAY_UTF8_TOP_PADDING=2
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/gat562_mesh_trial_tracker>
lib_deps =
  ${nrf52_base.lib_deps}
  https://github.com/Kongduino/Adafruit_nRFCrypto/archive/8cde7189b5ead9dcd49f72601b43b969c0bbc06e.zip
  https://github.com/adafruit/Adafruit_NeoPixel/archive/1.15.5.zip
  https://github.com/adafruit/Adafruit_BusIO/archive/refs/tags/1.17.4.zip
  https://github.com/adafruit/Adafruit_Sensor/archive/refs/tags/1.1.15.zip
  https://github.com/adafruit/Adafruit_BMP280_Library/archive/refs/tags/3.0.0.zip
  https://github.com/adafruit/Adafruit-BMP085-Library/archive/refs/tags/1.2.4.zip
  https://github.com/adafruit/Adafruit_BME280_Library/archive/refs/tags/2.3.0.zip
  https://github.com/adafruit/Adafruit_INA260/archive/refs/tags/1.5.3.zip
  https://github.com/adafruit/Adafruit_INA219/archive/refs/tags/1.2.3.zip
  https://github.com/adafruit/Adafruit_AHTX0/archive/refs/tags/2.0.6.zip
  https://github.com/Sensirion/arduino-sht/archive/refs/tags/v1.2.6.zip
  https://github.com/adafruit/Adafruit_MAX1704X/archive/refs/tags/1.0.3.zip
  https://github.com/ssp97/pinyin_simple_backend/archive/5c945d338468ecaba287ba27848d9130c01fda66e.zip
lib_ignore =
  ESP8266 and ESP32 OLED driver for SSD1306 displays
custom_meshtastic_display_name = GAT562 T9
custom_meshtastic_variant = GAT562 T9
