[env:tlora-t3s3-v1-mvsr]
custom_meshtastic_hw_model = 16
custom_meshtastic_hw_model_slug = TLORA_T3_S3
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 2
custom_meshtastic_display_name = LILYGO T-LoRa T3-S3 + MVSR Audio
custom_meshtastic_tags = LilyGo, Audio

extends = esp32s3_base
board = tlora-t3s3-v1
board_check = true
upload_protocol = esptool

build_flags =
  ${esp32s3_base.build_flags}
  -D TLORA_T3S3_V1
  -D AUDIO_I2S_DUAL=1
  -I variants/esp32s3/tlora_t3s3_v1_mvsr
