; RAK3401 + RAK13700 (LR2021) - same WisBlock core as rak3401-1watt; LoRa is LR2021
[env:rak3401-lr2021]
custom_meshtastic_hw_model = 117
custom_meshtastic_hw_model_slug = RAK3401
custom_meshtastic_architecture = nrf52840
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = RAK3401 LR2021
custom_meshtastic_images = rak3401.svg
custom_meshtastic_tags = RAK
custom_meshtastic_requires_dfu = true

extends = nrf52840_base
board = wiscore_rak4631
board_level = extra
board_check = true
build_flags = ${nrf52840_base.build_flags}
  -Ivariants/nrf52840/rak3401_lr2021
  -D RAK_4631
  -D RAK3401
  -D PRIVATE_HW
  -DRADIOLIB_EXCLUDE_SX126X=1
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/rak3401_lr2021> +<mesh/api/>
lib_deps =
  ${nrf52840_base.lib_deps}
  ${networking_base.lib_deps}
  # renovate: datasource=custom.pio depName=Melopero RV3028 packageName=melopero/library/Melopero RV3028
  melopero/Melopero RV3028@1.2.0
  # renovate: datasource=custom.pio depName=RAK NCP5623 RGB LED packageName=rakwireless/library/RAKwireless NCP5623 RGB LED library
  rakwireless/RAKwireless NCP5623 RGB LED library@1.0.3
  # renovate: datasource=custom.pio depName=RAK12035_SoilMoisture packageName=beegee-tokyo/library/RAK12035_SoilMoisture
  beegee-tokyo/RAK12035_SoilMoisture@1.0.4
  # renovate: datasource=git-refs depName=RAK12034-BMX160 packageName=https://github.com/RAKWireless/RAK12034-BMX160 gitBranch=main
  https://github.com/RAKWireless/RAK12034-BMX160/archive/dcead07ffa267d3c906e9ca4a1330ab989e957e2.zip
