[env:t-deck-max]
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = T_DECK_MAX
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 0
custom_meshtastic_display_name = LILYGO T-Deck MAX
custom_meshtastic_tags = LilyGo
custom_meshtastic_requires_dfu = true
custom_meshtastic_partition_scheme = 16MB

extends = esp32s3_base
board_level = extra
board = t-deck-pro
board_build.partitions = default_16MB.csv
upload_protocol = esptool

build_src_filter =
  ${esp32s3_base.build_src_filter}
  -<input/TDeckProKeyboard.cpp>
  -<motion/BHI260APSensor.cpp>
  -<concurrency/Lock.cpp>
  -<concurrency/LockGuard.cpp>
  +<../variants/esp32s3/t-deck-common>
  +<../variants/esp32s3/t-deck-max>
  +<../src/concurrency/Lock.cpp>
  +<../src/concurrency/LockGuard.cpp>

build_flags =
  ${esp32s3_base.build_flags}
  -I variants/esp32s3/t-deck-max
  -D T_DECK_MAX
  -D USE_EINK
  -D EINK_DISPLAY_MODEL=GxEPD2_310_GDEQ031T10
  -D EINK_WIDTH=240
  -D EINK_HEIGHT=320
  -D EINK_LIMIT_FASTREFRESH=10
  -D EINK_LIMIT_GHOSTING_PX=2000
  -D EINK_NOT_HIBERNATE

build_src_flags =
  -I variants/esp32s3/t-deck-common
  -include variants/esp32s3/t-deck-common/sdkconfig_compat.h
  -I.pio/libdeps/${PIOENV}/ArduinoThread
  -I.pio/libdeps/${PIOENV}/Nanopb
  -I.pio/libdeps/${PIOENV}/TinyGPSPlus/src
  -I.pio/libdeps/${PIOENV}/OneButton/src
  -I.pio/libdeps/${PIOENV}/TBPubSubClient/src
  -I.pio/libdeps/${PIOENV}/Crypto
  -iquote.pio/libdeps/${PIOENV}/Crypto
  -I".pio/libdeps/${PIOENV}/Adafruit BusIO"
  -I.pio/libdeps/${PIOENV}/arduino-fsm
  -I.pio/libdeps/${PIOENV}/ESP8266Audio/src
  -I.pio/libdeps/${PIOENV}/ESP8266SAM/src
  -I.pio/libdeps/${PIOENV}/NonBlockingRTTTL/src
  -I".pio/libdeps/${PIOENV}/Adafruit BME680 Library"
  -I".pio/libdeps/${PIOENV}/Adafruit BMP3XX Library"
  -I".pio/libdeps/${PIOENV}/Adafruit LIS3DH"
  -I".pio/libdeps/${PIOENV}/Adafruit LSM6DS"
  -I".pio/libdeps/${PIOENV}/Adafruit MAX1704X"
  -I".pio/libdeps/${PIOENV}/Adafruit MLX90614 Library"
  -I".pio/libdeps/${PIOENV}/Adafruit MPU6050"
  -I".pio/libdeps/${PIOENV}/Adafruit NeoPixel"
  -I".pio/libdeps/${PIOENV}/DFRobot_BMM150"
  -I".pio/libdeps/${PIOENV}/EmotiBit MLX90632/src"
  -I".pio/libdeps/${PIOENV}/ESP32 Codec2/src"
  -I".pio/libdeps/${PIOENV}/Grove - Laser PM2.5 Sensor HM3301/src"
  -I.pio/libdeps/${PIOENV}/libpax/lib/libpax
  -I".pio/libdeps/${PIOENV}/Sensirion Core/src"
  -I".pio/libdeps/${PIOENV}/Sensirion I2C SCD30/src"
  -I".pio/libdeps/${PIOENV}/Sensirion I2C SCD4x/src"
  -I".pio/libdeps/${PIOENV}/Sensirion I2C SFA3x/src"
  -I".pio/libdeps/${PIOENV}/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library/src"
  -I".pio/libdeps/${PIOENV}/SparkFun MMC5983MA Magnetometer Arduino Library/src"
  -I".pio/libdeps/${PIOENV}/SparkFun Qwiic Scale NAU7802 Arduino Library/src"
  -I".pio/libdeps/${PIOENV}/Adafruit DRV2605 Library"
  -I.pio/libdeps/${PIOENV}/GxEPD2/src
  -I".pio/libdeps/${PIOENV}/Adafruit GFX Library"
  -I".pio/libdeps/${PIOENV}/ESP8266 and ESP32 OLED driver for SSD1306 displays/src"

lib_deps =
  ${esp32s3_base.lib_deps}
  # renovate: datasource=custom.pio depName=GxEPD2 packageName=zinggjm/library/GxEPD2
  zinggjm/GxEPD2@1.6.9
  # renovate: datasource=git-refs depName=CSE_Touch packageName=https://github.com/CIRCUITSTATE/CSE_Touch gitBranch=main
  https://github.com/CIRCUITSTATE/CSE_Touch/archive/b44f23b6f870b848f1fbe453c190879bc6cfaafa.zip
  # renovate: datasource=github-tags depName=CSE_CST328 packageName=CIRCUITSTATE/CSE_CST328
  https://github.com/CIRCUITSTATE/CSE_CST328/archive/refs/tags/v0.0.4.zip
  # renovate: datasource=git-refs depName=BQ27220 packageName=https://github.com/mverch67/BQ27220 gitBranch=main
  https://github.com/mverch67/BQ27220/archive/07d92be846abd8a0258a50c23198dac0858b22ed.zip
  # renovate: datasource=custom.pio depName=Adafruit DRV2605 packageName=adafruit/library/Adafruit DRV2605 Library
  adafruit/Adafruit DRV2605 Library@1.2.4
  lewisxhe/SensorLib@0.3.4
  # renovate: datasource=git-refs depName=pschatzmann_arduino-audio-driver packageName=pschatzmann/arduino-audio-driver
  https://github.com/pschatzmann/arduino-audio-driver/archive/v0.3.0.zip
  # renovate: datasource=git-refs depName=ESP8266Audio packageName=https://github.com/meshtastic/ESP8266Audio gitBranch=meshtastic-2.0.0-dacfix
  https://github.com/meshtastic/ESP8266Audio/archive/343024632ee78d6216907b2353fc943a62422d80.zip
  # renovate: datasource=custom.pio depName=ESP8266SAM packageName=earlephilhower/library/ESP8266SAM
  earlephilhower/ESP8266SAM@1.1.0
