[env:t-deck-max]
custom_meshtastic_hw_model = 141
custom_meshtastic_hw_model_slug = T_DECK_MAX
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = LILYGO T-Deck Max
custom_meshtastic_images = tdeck_pro.svg
custom_meshtastic_tags = LilyGo
custom_meshtastic_requires_dfu = true
custom_meshtastic_partition_scheme = 16MB
custom_meshtastic_has_mui = false

extends = esp32s3_base
board = t-deck-pro
board_check = true
board_build.partitions = default_16MB.csv
upload_protocol = esptool

build_src_filter =
  ${esp32s3_base.build_src_filter}
  +<../variants/esp32s3/t-deck-max>

build_flags =
  ${esp32s3_base.build_flags} -I variants/esp32s3/t-deck-max -I variants/esp32s3/t-deck-max/HynTouch/src
  -D T_DECK_MAX
  -D BOARD_HAS_PSRAM
  -D USE_EINK
  -D EINK_DISPLAY_MODEL=GxEPD2_310_GDEQ031T10
  -D EINK_WIDTH=240
  -D EINK_HEIGHT=320
  -D EINK_LIMIT_FASTREFRESH=10
  -D EINK_LIMIT_GHOSTING_PX=2000
  -D EINK_NOT_HIBERNATE

lib_deps =
  ${esp32s3_base.lib_deps}
  # renovate: datasource=custom.pio depName=GxEPD2 packageName=zinggjm/library/GxEPD2
  zinggjm/GxEPD2@1.6.9
  # renovate: datasource=custom.pio depName=Adafruit DRV2605 packageName=adafruit/library/Adafruit DRV2605 Library
  adafruit/Adafruit DRV2605 Library@1.2.4
  # renovate: datasource=custom.pio depName=SensorLib packageName=lewisxhe/library/SensorLib
  lewisxhe/SensorLib@0.3.4
  # renovate: datasource=github-tags depName=pschatzmann_arduino-audio-driver packageName=pschatzmann/arduino-audio-driver
  https://github.com/pschatzmann/arduino-audio-driver/archive/v0.2.1.zip
  # renovate: datasource=git-refs depName=ESP8266Audio packageName=https://github.com/meshtastic/ESP8266Audio gitBranch=meshtastic-2.0.0-dacfix
  https://github.com/meshtastic/ESP8266Audio/archive/343024632ee78d6216907b2353fc943a62422d80.zip
  # renovate: datasource=custom.pio depName=ESP8266SAM packageName=earlephilhower/library/ESP8266SAM
  earlephilhower/ESP8266SAM@1.1.0
  # renovate: datasource=git-refs depName=BQ27220 packageName=https://github.com/mverch67/BQ27220 gitBranch=main
  https://github.com/mverch67/BQ27220/archive/07d92be846abd8a0258a50c23198dac0858b22ed.zip
