[env:t-echo-plus]
custom_meshtastic_hw_model = 33
custom_meshtastic_hw_model_slug = T_ECHO_PLUS
custom_meshtastic_architecture = nrf52840
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = LILYGO T-Echo Plus
custom_meshtastic_images = t-echo_plus.svg
custom_meshtastic_tags = LilyGo
custom_meshtastic_requires_dfu = true
custom_meshtastic_has_ink_hud = true

extends = nrf52840_base
board = t-echo
board_level = pr
board_check = true
debug_tool = jlink

build_flags = ${nrf52840_base.build_flags}
  -DTTGO_T_ECHO_PLUS
  -Ivariants/nrf52840/t-echo-plus
  -DEINK_DISPLAY_MODEL=GxEPD2_154_D67
  -DEINK_WIDTH=200
  -DEINK_HEIGHT=200
  -DUSE_EINK
  -DUSE_EINK_DYNAMICDISPLAY            ; Enable Dynamic EInk
  -DEINK_LIMIT_FASTREFRESH=20          ; How many consecutive fast-refreshes are permitted
  -DEINK_BACKGROUND_USES_FAST          ; (Optional) Use FAST refresh for both BACKGROUND and RESPONSIVE, until a limit is reached.
  -DI2C_NO_RESCAN

build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/t-echo-plus>

lib_deps =
  ${nrf52840_base.lib_deps}
  https://github.com/meshtastic/GxEPD2/archive/55f618961db45a23eff0233546430f1e5a80f63a.zip
  # renovate: datasource=custom.pio depName=PCF8563 packageName=lewisxhe/library/PCF8563_Library
  lewisxhe/PCF8563_Library@1.0.1
  # renovate: datasource=custom.pio depName=Adafruit DRV2605 packageName=adafruit/library/Adafruit DRV2605 Library
  adafruit/Adafruit DRV2605 Library@1.2.4
