#!/usr/bin/env bash
set -e

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

ENV_NAME="${1:-heltec-v3}"

echo "Building Meshtastic firmware..."
echo "Project directory: $PROJECT_DIR"
echo "PlatformIO environment: $ENV_NAME"

# Remove temporary CMakeLists.txt generated by pioarduino/ESP-IDF helper build.
if [ -f "CMakeLists.txt" ]; then
  echo "Removing temporary CMakeLists.txt..."
  rm -f CMakeLists.txt
fi

# Remove LTO flags from generated Arduino ESP32-S3 build script.
# pioarduino may inject -flto flags during Arduino library rebuild;
# on some heltec-v4 builds this causes undefined __atomic_fetch_add_4 at link time.
ARDUINO_S3_BUILD_SCRIPT="$HOME/.platformio/packages/framework-arduinoespressif32-libs/esp32s3/pioarduino-build.py"
if [ -f "$ARDUINO_S3_BUILD_SCRIPT" ]; then
  echo "Removing LTO flags from ESP32-S3 Arduino build script..."
  python3 - "$ARDUINO_S3_BUILD_SCRIPT" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text()
lines = text.splitlines()
filtered = [line for line in lines if "-flto" not in line]
path.write_text("\n".join(filtered) + "\n")
PY
fi

if command -v pio >/dev/null 2>&1; then
  pio run -e "$ENV_NAME"
else
  "$HOME/.platformio/penv/bin/pio" run -e "$ENV_NAME"
fi
