#!/usr/bin/env bash
set -e

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

echo "Building Meshtastic firmware for heltec-v3..."
echo "Project directory: $PROJECT_DIR"

# Remove temporary CMakeLists.txt generated by pioarduino/ESP-IDF helper build.
if [ -f "CMakeLists.txt" ]; then
  echo "Removing temporary CMakeLists.txt..."
  rm -f CMakeLists.txt
fi

if command -v pio >/dev/null 2>&1; then
  pio run
else
  "$HOME/.platformio/penv/bin/pio" run
fi
