#!/usr/bin/env bash
set -e

echo "Fixing local PlatformIO / ESP-IDF environment..."

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ESP_IDF_DIR="$HOME/.platformio/packages/framework-espidf"
ESPRESSIF_CACHE_DIR="$HOME/Library/Caches/Espressif/ComponentManager"

echo "Project directory: $PROJECT_DIR"

# Remove temporary CMakeLists.txt generated by pioarduino/ESP-IDF helper build.
if [ -f "$PROJECT_DIR/CMakeLists.txt" ]; then
  echo "Removing temporary project CMakeLists.txt..."
  rm -f "$PROJECT_DIR/CMakeLists.txt"
else
  echo "No temporary project CMakeLists.txt found."
fi

# Fix framework-espidf package if it exists but is not a valid git repo.
if [ -d "$ESP_IDF_DIR" ]; then
  echo "Checking framework-espidf git metadata..."

  cd "$ESP_IDF_DIR"

  if [ ! -d ".git" ]; then
    echo "Initializing git repository in framework-espidf..."
    git init
  fi

  if ! git config --get remote.origin.url >/dev/null 2>&1; then
    echo "Adding remote.origin.url..."
    git remote add origin https://github.com/pioarduino/esp-idf.git || true
  else
    echo "remote.origin.url already exists:"
    git config --get remote.origin.url
  fi

  git config user.email "local@platformio.invalid"
  git config user.name "PlatformIO Local"

  if ! git rev-parse --verify HEAD >/dev/null 2>&1; then
    echo "Creating empty local marker commit..."
    git commit --allow-empty -m "Local PlatformIO ESP-IDF marker"
  else
    echo "framework-espidf already has HEAD."
  fi
else
  echo "framework-espidf directory not found:"
  echo "$ESP_IDF_DIR"
  echo "Run PlatformIO once, then run this script again if this problem appears."
fi

# Remove damaged Espressif ComponentManager bare git caches.
if [ -d "$ESPRESSIF_CACHE_DIR" ]; then
  echo "Cleaning Espressif ComponentManager bare git cache..."
  find "$ESPRESSIF_CACHE_DIR" -maxdepth 1 -type d -name "b_git_*" -print -exec rm -rf {} +
else
  echo "Espressif ComponentManager cache directory not found, skipping."
fi

echo "Local PlatformIO / ESP-IDF environment fix completed."
