[env:heltec-v4-lifepo4-12v]
extends = env:heltec-v4
board_level = extra
build_flags = ${env:heltec-v4.build_flags}
  -D NUM_CELLS=4
  -D OCV_ARRAY="3400, 3350, 3320, 3290, 3270, 3260, 3250, 3230, 3200, 3120, 3000"
