[env:nrf54l15dk]
custom_meshtastic_hw_model = 132
custom_meshtastic_hw_model_slug = NRF54L15_DK
custom_meshtastic_architecture = nrf54l15
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = Nordic nRF54L15-DK

extends = nrf54l15_base
board = nrf54l15dk
board_level = extra
debug_tool = jlink
upload_protocol = jlink
board_runner_args_jlink = --device nRF54L15_xxAA --speed 4000

build_flags = ${nrf54l15_base.build_flags}
  -Ivariants/nrf54l15/nrf54l15dk
  -DNRF54L15_DK

build_src_filter = ${nrf54l15_base.build_src_filter}
  +<../variants/nrf54l15/nrf54l15dk>
