[crowpanel_advance_v12_base]
extends = crowpanel_base
build_flags =
  -I variants/esp32s3/elecrow_panel_advance_v12
  ${crowpanel_base.build_flags}
  -UUSE_PIN_BUZZER
  -D CROW_SELECT=3
  -D HAS_ELECROW_STC
  -D HAS_ELECROW_STC_BUZZER
  -D SDCARD_CS=7
  -D LGFX_DRIVER=LGFX_ELECROW70
  -D GFX_DRIVER_INC=\"graphics/LGFX/LGFX_ELECROW70.h\"
  -D DISPLAY_SET_RESOLUTION

[env:elecrow-adv1-43-50-70-tft-v12]
custom_meshtastic_hw_model = 97
custom_meshtastic_hw_model_slug = CROWPANEL
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = Crowpanel Adv 4.3/5.0/7.0 TFT v1.2+
custom_meshtastic_images = crowpanel_5_0.svg, crowpanel_7_0.svg
custom_meshtastic_tags = Elecrow
custom_meshtastic_requires_dfu = true
custom_meshtastic_partition_scheme = 16MB
custom_meshtastic_has_mui = true

extends = crowpanel_advance_v12_base
board_level = release
build_flags =
  ${crowpanel_advance_v12_base.build_flags}
  -D VIEW_320x240
  -D DISPLAY_SIZE=800x480
