; Waveshare ESP32-C3-Zero Development Board
; https://docs.waveshare.com/ESP32-C3-Zero
[env:esp32c3_zero]
extends = esp32c3_base
board = esp32-c3-devkitm-1
build_flags =
  ${esp32c3_base.build_flags}
  -D PRIVATE_HW
  -I variants/esp32c3/diy/esp32c3_zero
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
custom_meshtastic_support_level = 3
board_level = extra
