#ifdef MESHTASTIC_INCLUDE_INKHUD

/*

Set of end-point actions for the Menu Applet

Added as menu entries in MenuApplet::showPage
Behaviors assigned in MenuApplet::execute

*/

#pragma once

#include "configuration.h"

namespace NicheGraphics::InkHUD
{

enum MenuAction {
    NO_ACTION,
    SEND_PING,
    STORE_CANNEDMESSAGE_SELECTION,
    SEND_CANNEDMESSAGE,
    SHUTDOWN,
    NEXT_TILE,
    TOGGLE_BACKLIGHT,
    TOGGLE_GPS,
    ENABLE_BLUETOOTH,
    TOGGLE_APPLET,
    TOGGLE_AUTOSHOW_APPLET,
    SET_RECENTS,
    ROTATE,
    LAYOUT,
    TOGGLE_BATTERY_ICON,
    TOGGLE_NOTIFICATIONS,
    TOGGLE_INVERT_COLOR,
    TOGGLE_12H_CLOCK,
    // Regions
    SET_REGION_US,
    SET_REGION_EU_868,
    SET_REGION_EU_433,
    SET_REGION_CN,
    SET_REGION_JP,
    SET_REGION_ANZ,
    SET_REGION_KR,
    SET_REGION_TW,
    SET_REGION_RU,
    SET_REGION_IN,
    SET_REGION_NZ_865,
    SET_REGION_TH,
    SET_REGION_LORA_24,
    SET_REGION_UA_433,
    SET_REGION_UA_868,
    SET_REGION_MY_433,
    SET_REGION_MY_919,
    SET_REGION_SG_923,
    SET_REGION_PH_433,
    SET_REGION_PH_868,
    SET_REGION_PH_915,
    SET_REGION_ANZ_433,
    SET_REGION_KZ_433,
    SET_REGION_KZ_863,
    SET_REGION_NP_865,
    SET_REGION_BR_902,
    // Device Roles
    SET_ROLE_CLIENT,
    SET_ROLE_CLIENT_MUTE,
    SET_ROLE_ROUTER,
    SET_ROLE_REPEATER,
    // Presets
    SET_PRESET_LONG_SLOW,
    SET_PRESET_LONG_MODERATE,
    SET_PRESET_LONG_FAST,
    SET_PRESET_MEDIUM_SLOW,
    SET_PRESET_MEDIUM_FAST,
    SET_PRESET_SHORT_SLOW,
    SET_PRESET_SHORT_FAST,
    SET_PRESET_SHORT_TURBO,
};

} // namespace NicheGraphics::InkHUD

#endif