(()=>{var m=Object.defineProperty;var u=(a,e,s)=>e in a?m(a,e,{enumerable:!0,configurable:!0,writable:!0,value:s}):a[e]=s;var d=(a,e,s)=>u(a,typeof e!="symbol"?e+"":e,s);var g=class{constructor(){d(this,"usernameToNodeId",{});d(this,"nodeIdToUsername",{});d(this,"mailMessages",[]);d(this,"newsMessages",[]);d(this,"mailReadMarkers",{});d(this,"newsReadMarkers",{});d(this,"nextMailId",1);d(this,"nextNewsId",1)}registerUser(e,s){let t=s.toLowerCase();if(this.isUsernameTaken(t))return!1;let r=this.nodeIdToUsername[e];return r&&delete this.usernameToNodeId[r],this.usernameToNodeId[t]=e,this.nodeIdToUsername[e]=t,!0}getUserByNodeId(e){return this.nodeIdToUsername[e]||null}getUserByUsername(e){let s=e.toLowerCase();return this.usernameToNodeId[s]!==void 0?this.usernameToNodeId[s]:null}isUsernameTaken(e){return this.usernameToNodeId[e.toLowerCase()]!==void 0}addMail(e,s,t){this.mailMessages.push({to:e,from:s,body:t,timestamp:Date.now(),id:this.nextMailId++})}getPendingMail(e){let s=this.mailReadMarkers[e]||{};return this.mailMessages.filter(t=>t.to===e&&!s[t.id])}markMailAsRead(e,s){this.mailReadMarkers[e]||(this.mailReadMarkers[e]={});let t=this.mailReadMarkers[e];s.forEach(r=>t[r]=!0)}addNews(e,s){this.newsMessages.push({from:e,body:s,timestamp:Date.now(),id:this.nextNewsId++})}getUnreadNews(e){let s=this.newsReadMarkers[e]||{};return this.newsMessages.filter(t=>!s[t.id])}markNewsAsRead(e,s){this.newsReadMarkers[e]||(this.newsReadMarkers[e]={});let t=this.newsReadMarkers[e];s.forEach(r=>t[r]=!0)}},l=class{constructor(e){this.storage=e}handleCommand(e,s){let t=s.trim();return console.log(`BBSCommandHandler: handleCommand: ${t}`),t.startsWith("/register ")?this.handleRegister(e,t.substring(10).trim()):t.startsWith("/mail ")?this.handleSendMail(e,t.substring(6).trim()):t==="/mail"?this.handleFetchMail(e):t==="/whoami"?this.handleWhoAmI(e):t.startsWith("/news ")?this.handlePostNews(e,t.substring(6).trim()):t==="/news"?this.handleFetchNews(e):this.handleWelcome(e)}handleRegister(e,s){return!s||s.length===0?"Usage: /register <username>":/^[a-zA-Z0-9_]+$/.test(s)?this.storage.registerUser(e,s)?`Welcome to uBBS, ${s}!`:`Error: Username "${s}" is already taken`:"Error: Username must be alphanumeric (with underscores)"}handleSendMail(e,s){let t=s.indexOf(" ");if(t===-1)return"Usage: /mail <username> <body>";let r=s.substring(0,t),i=s.substring(t+1).trim();if(!i)return"Error: Message body cannot be empty";let n=this.storage.getUserByUsername(r);return n?(this.storage.addMail(n,e,i),`Mail sent to ${r}`):`Error: User "${r}" not found`}handleFetchMail(e){let s=this.storage.getPendingMail(e);if(s.length===0)return"No pending mail";this.storage.markMailAsRead(e,s.map(r=>r.id));let t=s.map((r,i)=>{let n=this.storage.getUserByNodeId(r.from)||`node:${r.from.toString(16)}`,o=new Date(r.timestamp).toISOString().split("T")[0];return`${i+1}. From ${n} (${o}):
   ${r.body}`});return`You have ${s.length} message(s):

${t.join(`

`)}`}handleWhoAmI(e){let s=this.storage.getUserByNodeId(e);return s?`You are: ${s}`:"Not registered. Use /register <username> to register"}handlePostNews(e,s){return!s||s.length===0?"Usage: /news <body>":this.storage.getUserByNodeId(e)?(this.storage.addNews(e,s),"News posted successfully"):"Error: You must register before posting news. Use /register <username>"}handleFetchNews(e){let s=this.storage.getUnreadNews(e);if(s.length===0)return"No unread news";this.storage.markNewsAsRead(e,s.map(r=>r.id));let t=s.map((r,i)=>{let n=this.storage.getUserByNodeId(r.from)||`node:${r.from.toString(16)}`,o=new Date(r.timestamp).toISOString().split("T")[0];return`${i+1}. ${n} (${o}):
   ${r.body}`});return`Unread news (${s.length}):

${t.join(`

`)}`}handleWelcome(e){let s=this.storage.getPendingMail(e).length,t=this.storage.getUnreadNews(e).length,r=this.storage.getUserByNodeId(e),i=r?`Welcome back, ${r}!`:"Welcome to uBBS!",n=[];return s>0&&n.push(`${s} unread message${s===1?"":"s"}`),t>0&&n.push(`${t} unread news item${t===1?"":"s"}`),n.length>0?`${i}
You have ${n.join(" and ")}.`:`${i}
No unread items.`}},h=new g,N=new l(h);Meshtastic.onTextMessage((a,e)=>{let s=N.handleCommand(a,e);console.log(`uBBS response: ${s}`),Meshtastic.sendTextMessage(a,s)});})();
