; IKOKA STICK 0.3.0 with EBYTE E22-400M33S (SX1268)
; https://ndoo.sg/projects:amateur_radio:meshtastic:diy_devices:ikoka_stick
[env:ikoka_stick_0_3_0]
extends = nrf52840_base
board = xiao_ble_sense
board_level = extra
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/ikoka_stick_0_3_0
  -I src/platform/nrf52/softdevice
  -I src/platform/nrf52/softdevice/nrf52
  -DIKOKA_STICK_0_3_0
  -DPRIVATE_HW
  -DEBYTE_E22
  -DEBYTE_E22_400M33S
  -DCONFIG_NFCT_PINS_AS_GPIOS=1
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/ikoka_stick_0_3_0>
debug_tool = jlink
; If not set we will default to uploading over serial (first it forces bootloader entry by talking 1200bps to cdcacm)
;upload_protocol = jlink

[env:ikoka_stick_0_3_0_rf_test]
extends = env:ikoka_stick_0_3_0
build_flags = ${env:ikoka_stick_0_3_0.build_flags}
  -DMESHTASTIC_RF_TEST_FIRMWARE
