[env:heltec-rcc6]
custom_meshtastic_hw_model = 143
custom_meshtastic_hw_model_slug = HELTEC_RCC6
custom_meshtastic_architecture = esp32-c6
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = Heltec RCC6
custom_meshtastic_tags = Heltec
custom_meshtastic_has_mui = false

extends = esp32c6_base
board = heltec-rcc6
board_level = pr
board_build.partitions = default_16MB.csv
upload_protocol = esptool

build_flags =
  ${esp32c6_base.build_flags}
  -D HELTEC_RCC6
  -I variants/esp32c6/heltec_rcc6
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DMESHTASTIC_EXCLUDE_AUDIO=1

lib_deps =
  ${esp32c6_base.lib_deps}
  https://github.com/Quency-D/Arduino_GFX/archive/4d5afb05ce70a51895fe65efc7838d606b2a95a7.zip

lib_ignore =
  ${esp32c6_base.lib_ignore}
  ESP32 Codec2
