[env:seeed_mesh_tracker_X1]
custom_meshtastic_support_level = 1
custom_meshtastic_images = seeed-mesh-tracker-x1.svg
custom_meshtastic_tags = Seeed
custom_meshtastic_hw_model = 128
custom_meshtastic_hw_model_slug = MESH_TRACKER_X1
custom_meshtastic_architecture = nrf52840
custom_meshtastic_display_name = Seeed SenseCAP Mesh-Tracker-X1
custom_meshtastic_actively_supported = true

extends = nrf52840_base
board = mesh-tracker-x1
board_level = pr
build_flags = ${nrf52840_base.build_flags}
  -Ivariants/nrf52840/seeed_mesh_tracker_X1
  -Isrc/platform/nrf52/softdevice
  -Isrc/platform/nrf52/softdevice/nrf52
  -DMESH_TRACKER_X1
  -DCONFIG_NFCT_PINS_AS_GPIOS=1
  -DMESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR_EXTERNAL=1
  -DMESHTASTIC_EXCLUDE_CANNEDMESSAGES=1
  -DMESHTASTIC_EXCLUDE_SCREEN=1
  -DMESHTASTIC_EXCLUDE_DETECTIONSENSOR=1
  -DMESHTASTIC_EXCLUDE_WIFI=1
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/seeed_mesh_tracker_X1>
lib_deps = 
  ${nrf52840_base.lib_deps}
  adafruit/Adafruit DRV2605 Library@1.2.4

debug_tool = jlink
; If not set we will default to uploading over serial (first it forces bootloader entry by talking 1200bps to cdcacm)
upload_protocol = nrfutil
