/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0 */

#include "mesh.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mesh_Position, mesh_Position, AUTO)


PB_BIND(mesh_Time, mesh_Time, AUTO)


PB_BIND(mesh_Data, mesh_Data, AUTO)


PB_BIND(mesh_User, mesh_User, AUTO)


PB_BIND(mesh_WantNodeNum, mesh_WantNodeNum, AUTO)


PB_BIND(mesh_DenyNodeNum, mesh_DenyNodeNum, AUTO)


PB_BIND(mesh_SubPacket, mesh_SubPacket, AUTO)


PB_BIND(mesh_MeshPayload, mesh_MeshPayload, 2)


PB_BIND(mesh_MeshPacket, mesh_MeshPacket, 2)


PB_BIND(mesh_RadioConfig, mesh_RadioConfig, 2)


PB_BIND(mesh_NodeInfo, mesh_NodeInfo, AUTO)


PB_BIND(mesh_DeviceState, mesh_DeviceState, 4)


PB_BIND(mesh_FromRadio, mesh_FromRadio, 2)


PB_BIND(mesh_ToRadio, mesh_ToRadio, 2)


PB_BIND(mesh_ToRadio_WantNodes, mesh_ToRadio_WantNodes, AUTO)




#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

