[env:t-echo-card]
extends = nrf52840_base
board = t-echo
board_level = extra
debug_tool = jlink

build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/t-echo-card
  -D PRIVATE_HW
  -D T_ECHO_CARD

build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/t-echo-card>
