[env:seeed-xiao-c6]
custom_meshtastic_hw_model = 0000
custom_meshtastic_hw_model_slug = SEEED_XIAO_C6
custom_meshtastic_architecture = esp32-c6
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = Seeed Xiao ESP32-C6
custom_meshtastic_images = seeed-xiao-c6.svg
custom_meshtastic_tags = Seeed
custom_meshtastic_requires_dfu = false
custom_meshtastic_partition_scheme = 4MB

extends = esp32c6_base
board = seeed-xiao-c6
board_level = pr
board_check = true
board_build.partitions = huge_app.csv
upload_protocol = esptool
upload_speed = 460800
build_flags =
  ${esp32c6_base.build_flags}
  -D SEEED_XIAO_C6
  -I variants/esp32c6/seeed_xiao_c6
