[env:seeed-xiao-c6]
custom_meshtastic_architecture = esp32-c6
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = Seeed XIAO ESP32-C6
custom_meshtastic_tags = Seeed

extends = esp32c6_base
board = seeed-xiao-c6
board_level = extra
upload_protocol = esptool
upload_speed = 921600
build_unflags =
  -DLED_BUILTIN=-1
  -DHAS_BLUETOOTH=0
  -DMESHTASTIC_EXCLUDE_BLUETOOTH
lib_deps =
  ${esp32c6_base.lib_deps}
  # renovate: datasource=custom.pio depName=NimBLE-Arduino packageName=h2zero/library/NimBLE-Arduino
  h2zero/NimBLE-Arduino@2.3.7
build_flags =
  ${esp32c6_base.build_flags}
  -D SEEED_XIAO_C6
  -I variants/esp32c6/seeed_xiao_c6
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DHAS_BLUETOOTH=1
  -DCONFIG_BT_NIMBLE_EXT_ADV=1
  -DCONFIG_BT_NIMBLE_MAX_EXT_ADV_INSTANCES=2
  -DNIMBLE_TWO
lib_ignore =
  NonBlockingRTTTL
  libpax