name: Build_personal
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -U platformio
      - run: pio run -e supermini_wio_sx1262_v1
      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/supermini_wio_sx1262_v1/firmware*.bin
