name: LSM Tests

on: [push, pull_request]

jobs:
  test-lsm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Run LSM Tests
        run: ./run_lsm_tests.sh
