name: Pull Request
on: [pull_request]
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-24.04
    permissions:
      contents: read # For repo checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Trunk Check
        uses: trunk-io/trunk-action@v2.0.0
        with:
          cache: false
