[env:makerfabs_pucky]
custom_meshtastic_hw_model = 124
custom_meshtastic_hw_model_slug = Hockey_Puck
custom_meshtastic_architecture = nrf52840
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = Makerfabs Hockey Puck
custom_meshtastic_images = rak4631.svg, rak4631_case.svg
custom_meshtastic_tags = Makerfabs

extends = nrf52840_base
board = makerfabs_pucky
board_level = pr
board_check = true
build_type = release
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/makerfabs_pucky
  -D Hockey_Puck
  -DMESHTASTIC_USE_EINK_UI=0
  -DMESHTASTIC_HAS_SCREEN=0
  -DMESHTASTIC_HAS_GPS=1
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_SX126X=1
  -DRADIOLIB_EXCLUDE_LR11X0=0
build_src_filter = ${nrf52_base.build_src_filter} \
  +<../variants/nrf52840/makerfabs_pucky> \
  +<mesh/api/> \
  +<mqtt/> \
lib_deps = 
  ${nrf52840_base.lib_deps}
  ${networking_base.lib_deps}
  # TODO renovate
  https://github.com/meshtastic/QMA6100P_Arduino_Library/archive/14c900b8b2e4feaac5007a7e41e0c1b7f0841136.zip

; If not set we will default to uploading over serial (first it forces bootloader entry by talking 1200bps to cdcacm)
; Note: as of 6/2013 the serial/bootloader based programming takes approximately 30 seconds
;upload_protocol = jlink

; Allows programming and debug via the RAK NanoDAP as the default debugger tool for the RAK4631 (it is only $10!)
; programming time is about the same as the bootloader version.
; For information on this see the meshtastic developers documentation for "Development on the NRF52"
[env:makerfabs_pucky_dbg]
extends = env:makerfabs_pucky
board_level = extra

; if the builtin version of openocd has a buggy version of semihosting, so use the external version
; platform_packages = platformio/tool-openocd@3.1200.0

build_flags =
  ${env:makerfabs_pucky.build_flags}
  -D USE_SEMIHOSTING

lib_deps =
  ${env:makerfabs_pucky.lib_deps}
  # TODO renovate
  https://github.com/geeksville/Armduino-Semihosting/archive/35b538fdf208c3530c1434cd099a08e486672ee4.zip

; NOTE: the pyocd support for semihosting is buggy.  So I switched to using the builtin platformio support for the stlink adapter which worked much better.
; However the built in openocd version in platformio has buggy support for TCP to semihosting. 
;
; So I'm now trying the external openocd - but the openocd scripts for nrf52.cfg assume you are using a DAP adapter not an STLINK adapter.
; In theory I could change those scripts.  But for now I'm trying going back to a DAP adapter but with the external openocd.

upload_protocol = stlink
; eventually use platformio/tool-pyocd@2.3600.0 instad
;upload_protocol = custom
;upload_command = pyocd flash -t nrf52840 $UPLOADERFLAGS $SOURCE
