[env:t-impulse-plus]
extends = nrf52840_base
board = t-impulse-plus

build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/t-impulse-plus
  -D T_IMPULSE_PLUS

build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/t-impulse-plus>
